### ISSUE TITLE
Aula 08 - Resolução dos exercícios

### ISSUE THREAD

**Issue by sergioribeiros** [cwi-reset/edicao-02-qualificatoria#16]
Alguém sabe me explicar por que "index" na resolução dos exercícios?
```javascript
for (index = 0; index < bandas.length; index++) {
    console.info(bandas[index])

for (index = 0; index < valores.length; index++) {
    soma += valores[index]
```

**Comment by AlexandreSNeto** [comment]
Olá Sérgio, tudo bem?

O termo "index" é bastante usado para referenciar o "índice" (tradução literal) de uma iteração. 

Na prática é apenas o nome da variável. Poderia ser "i" ou "batata", o resultado seria o mesmo. 

Ficou claro?

**Comment by Pnoronha3647** [comment]
Obrigado aos 2 colegas... para mim, tanto as dúvidas como as respostas são aprendizados.

**Comment by AlexandreSNeto** [comment]
Tais minha explicação tenha ficado um pouco vaga.

O "índex" é uma variável que usamos para identificar em qual iteração estamos dentro da estrutura de repetição.

Por exemplo, no código:

`for(index=0, index <= 10; index++)`

ao executar a primeira vez, o index receber o valor 0 (pois indicamos isso no primeiro parâmetro)

Na próxima ele é 1 (pois indicamos no terceiro paramento que a cada iteração o index será acrescido de 1), e assim sucessivamente (até chegar em 10, que foi a regra definida no segundo parâmetro)

**Comment by Felipe-F-Coelho** [comment]
Olá, Boa noite turma!

No exercício 02 verifiquei que a resolução logo abaixo tem uma variável chamado "soma", fui pesquisar mais a fundo e descobri que essa variável irá absorver todos os valores inseridos na array, por esse motivo é importante que a mesma tenha o valor de "= 0"

" soma = 0 e soma += valores[index]"
```
valores = [1, 2, 3, 5, 8, 13, 21, 23, 34, 55]

soma = 0
for (index = 0; index < valores.length; index++) {
    soma += valores[index]
}

media = soma / valores.length
console.log(media)
```
Estou postando esse comentário caso tenha algum colega com a mesma dúvida.

Abraços,
Felipe Coelho

**Comment by AlexandreSNeto** [comment]
> Olá, Boa noite turma!
> 
> No exercício 02 verifiquei que a resolução logo abaixo tem uma variável chamado "soma", fui pesquisar mais a fundo e descobri que essa variável irá absorver todos os valores inseridos na array, por esse motivo é importante que a mesma tenha o valor de "= 0"
> 
> " soma = 0 e soma += valores[index]"
> 
> ```
> valores = [1, 2, 3, 5, 8, 13, 21, 23, 34, 55]
> 
> soma = 0
> for (index = 0; index < valores.length; index++) {
>     soma += valores[index]
> }
> 
> media = soma / valores.length
> console.log(media)
> ```
> 
> Estou postando esse comentário caso tenha algum colega com a mesma dúvida.
> 
> Abraços,
> Felipe Coelho

Boa Felipe, vamos ajustar na solução proposta. 

Apenas uma observação, você poderia ter criado uma nova Issue a respeito deses item. A issue que estamos usando aqui é referente ao exercício 8, sacou ?

**Comment by sergioribeiros** [comment]
Muito obrigado pessoal, agora ficou bastante claro :D

**Comment by CarlosBueno3000** [comment]
Boa tarde e um Feliz Ano Novo Pessoal!

Briguei muito aqui, mas fiz o exercício 3 utilizando "While", que foi minha ideia inicial mesmo. Estava colocando os comandos de impressão após o laço de repetição e não entendia porque o JavaScript ignorava o valor da comparação de nome, resultando sempre em "True". Cheguei a imprimir somente a resposta (true ou false) após o laço e estava comparando corretamente.

Enfim, saiu depois de colocar uma igualdade à mais, pois eu estava usando apenas [ if (nomeComum **=** true)...], enquanto deveria usar [ if (nomeComum **==** true)...] ou poderia fazer apenas igual a resolução proposta, no final, apenas [ if (nomeComum)...] que já é o conjunto verdade, pelo que entendi. 

Abaixo, a solução:

nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia", "Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia", "Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina", "Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia", "Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda", "Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]

meuNome = "Carlos"

pos = 0

nomeComum = false

while (pos < nomesComuns.length)
 {
  if (meuNome === nomesComuns[pos++]){
    nomeComum = true
    }
  }
if (nomeComum == true){
  console.log("É, nome comum :P")
  }
else{ console.log("Diferentão, hein? xD")}

**Comment by freycoding** [comment]
Isso mesmo @CarlosBueno3000 .

Como viu na prática, o uso correto da sintaxe na programação faz diferença.

O uso do igual pode ser usado tanto para atribuir valor a uma variável quanto para comparação de variáveis. 
No seu caso, não funcionou em um primeiro momento, pois ao escrever `if (nomeComum = true)` você estava atribuindo o valor true a variável nomeComum, o que é uma instrução verdadeira.
Por isso que para validar se uma variável contém o valor correto devemos usar `==` que é o operador de comparação.

No teu caso, como também apontou, poderia utilizar somente `if (nomeComum)` que seria uma instrução verdadeira também. 
Esta é uma característica da linguagem Javascript, que verifica então se a variável testada esta: definida, não nula e/ou verdadeira.

Resumindo:

```
if(nomeComum = true) //Atribuição de valor: por ser uma instrução valida, é verdadeira
if(nomeComum == true) //Comparação de valores: nomeComum sendo uma variavel que contém o valor true, é verdadeira
if(nomeComum) //Comparação de valor: sendo nomeComum, uma variável definida, não nula e/ou verdadeira, portanto é verdadeira
```

**Comment by Lorandi** [comment]
Gostei de ver a soluções de vocês. É muito legal como um código pode ser resolvido de maneiras tão diferentes para chegar em um mesmo resultado. 

O meu ficou assim:

`nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia", 
"Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia", 
"Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina", 
"Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia", 
"Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda", 
"Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]

nomeVerificar = "Isabela";  //inserir nome que será verificado

for (i = 0; i<nomesComuns.length; i++){
    if(nomeVerificar==nomesComuns[i]){
        verificador = true;
        break;
    }else{
        verificador = false;
    }
}

if(verificador==true){
    console.log("É, nome comum :P")
}else{
    console.log("Diferentão, hein? XD")
}`

Olhando os outros códigos, vejo que poderia ser mais econômico ao codar. Mas é isso aí, aos poucos vamos pegando o jeito.

**Comment by joprestes** [comment]
Boa tarde Pessoal!

Segue minhas resoluções para os exercícios propostos na aula 08

`<
//Exercícios
console.log("Aula 08 - Exercício 1")
console.log("")
console.log("Crie um array de 5 posições com quaisquer valores. ")
console.log("Utilize qualquer estrutura de repetição apresentada no vídeo para exibir todos os valores do array;")
console.log("")

nomes = ["Joelma", "Rodrigo", "Lucas", "Camila", "Joice"]

console.log(" Utilizando o Comando de repetição FOR ")
console.log("")

for (let indice = 0; indice < nomes.length; indice++) {
    posicao = indice + 1
    console.log("Nome " + posicao + ": " + nomes[indice]);

}
console.log("")
indice = 0
console.log(" Utilizando o comando de Repetição While ")
console.log("")
while (indice < nomes.length) {
    posicao = indice + 1
    console.log("Nome " + posicao + ": " + nomes[indice])
    indice++
}
console.log("")


console.log("")
indice = 0
console.log(" Utilizando o comando de Repetição  Do While ")
console.log("")
do {
    posicao = indice + 1
    console.log("Nome " + posicao + ": " + nomes[indice])
    indice++
}
while (indice < nomes.length) {}
console.log("")
console.log("Fim do Exercício 1")
console.log("")

console.log("Aula 08 - Exercício 2")
console.log("")
console.log("Crie um algoritmo capaz de calcular a média aritmética de um array com qualquer quantidade")
console.log("de elementos numéricos. Para fins de exemplo, o resultado do algoritmo com um array de valores 1, 2, 3, 5, 8, 13, 21, 23, 34, 55 deve ser 16.5.")
console.log("Procure usar uma estrutura de repetição diferente da que você usou para fazer o exercício anterior;")
console.log("")

//Declarações

numeros = [55, 27, 39, 52, 8, 13, 21, 23, 34, 55]
tamanhoDeNumeros = numeros.length
soma = 0
media = 0


console.log(" Apresentaremos a média aritmétida de " + tamanhoDeNumeros + " números.")
console.log("Os números são: " + numeros)
console.log("")

//Execução de comandos de repetição
console.log("Executando com For")

for (indice = 0; indice < numeros.length; indice++) {

    soma = numeros[indice] + soma
    media = soma / tamanhoDeNumeros
}
console.log(" A média entre os números é: " + media.toFixed(2) + ".")
console.log("")

console.log("Executando com While")

while (indice < numeros.length) {

    soma = numeros[indice] + soma
    media = soma / tamanhoDeNumeros
    indice++

}
console.log(" A média entre os números é: " + media.toFixed(2) + ".")
console.log("")

console.log("Executando com Do... While")
    //zerando as variáveis

indice = 0
soma = 0
media = 0


do {
    soma = numeros[indice] + soma
    media = soma / numeros.length
    indice++

}
while (indice < numeros.length)
console.log(" A média dos números é: " + media.toFixed(2) + ".")
console.log("")
console.log("Fim do Exercício 2")
console.log("")
    //--------------------------------------------------------------

console.log("Aula 08 - Exercício 3")
console.log("")
console.log("Considerando a lista dos 60 nomes mais comuns no Brasil nos últimos 10 anos, crie um algoritmo para verificar se seu nome está lá.")
console.log("Se sim, exiba a mensagem: É, nome comum :P. Se não, exiba a mensagem: Diferentão, hein? XD.")

console.log(" Utilizando o Comando de repetição FOR ")
console.log("")
    // Declaração das variáveis

nomesMaisComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia",
    "Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia",
    "Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina",
    "Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia",
    "Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda",
    "Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"
]
nome = "Lorena"
index = 0
nomeComum = false
tamanhoNomes = nomesMaisComuns.length


//Execução



for (index = 0; index < nomesMaisComuns.length; index++) {

    if (nome == nomesMaisComuns[index]) {
        nomeComum = true
        break

    }
}

if (nomeComum) {
    console.log(" O nome que seus pais lhe deram " + nome + " é comum. :P ")
} else
    console.log("O nome que seus pais lhe deram " + nome + " é diferentão hein! XD")
console.log("Fim do  FOR -- |For funcionando")
console.log("")



console.log("Utilizando o comando de repetição While")
console.log("")

//Declaração das Variáveis
meuNome = "Joelma"
index = 0
nomeComum1 = false

//Execução
while (index < nomesMaisComuns.length) {
    if (meuNome == nomesMaisComuns[index]) {
        nomeComum1 = true
        break
    }
    index++

}
if (nomeComum1) {
    console.log(" O nome que seus pais lhe deram " + meuNome + " é comum. :P ")
} else
    console.log("O nome que seus pais lhe deram " + meuNome + " é diferentão hein! XD")
console.log("Fim do  WHILE *While Funcionando*")
console.log("")



console.log(" Utilizando o Comando de repetição DO... WHILE ")
console.log("")
    // declaração de  variáveis
nomeMeu = "Jojo"
index = 0
nomeComum2 = false


do {
    if (nomeMeu == nomesMaisComuns[index]) {
        nomeComum2 = true
        break
    }
    index++

} while (index < nomesMaisComuns.length);

switch (nomeComum2) {
    case true:
        console.log(" O nome que seus pais lhe deram " + nomeMeu + " é comum. :P ")
        break
    case false:
        console.log("O nome que seus pais lhe deram " + nomeMeu + " é diferentão hein! XD")
        break
}
console.log("Fim do comando DO... WHILE * DO..While Funcionando*")
console.log("")

//FIM DOS EXERCÍCIOS DE COMANDO DE REPETIÇÃO>
`

**Comment by gilvangobbato** [comment]
Boa tarde pessoal,

@GuiMichel gostei da sua solução, verifiquei aqui apenas um detalhe que, a pesar de não interferir no seu código, achei legal comentar.
Para realizar este laço de repetição você instanciou a variável "num":
```
let num = 0

for(num=0; num<linguagem.length; num++){
  console.log(linguagem[num])
}
```
Porém para esse tipo de laço não é necessário instanciar a variável que será utilizada como índice, pois ela irá assumir o valor definido no for, por exemplo:
```
for(num=0; num<linguagem.length; num++){ console.log(linguagem[num]) } //instância a variável num e atribui zero como número inicial
for(num=5; num<linguagem.length; num++){ console.log(linguagem[num]) } //Nesse caso instância a variável num e atribui a ela o valor inicial = 5
```
Vale ressaltar que esta variável tem validade apenas dentro do "for" e não é aconselhado que seu valor seja alterado pelo código para garantir sua integridade.

**Comment by vitorassi** [comment]
> Boa tarde Pessoal!
> 
> Segue minhas resoluções para os exercícios propostos na aula 08
> 
> 
> ```js
> //Exercícios
> console.log("Aula 08 - Exercício 1")
> console.log("")
> console.log("Crie um array de 5 posições com quaisquer valores. ")
> console.log("Utilize qualquer estrutura de repetição apresentada no vídeo para exibir todos os valores do array;")
> console.log("")
> 
> nomes  =  [ "Joelma" ,  "Rodrigo" ,  "Lucas" ,  "Camila" ,  "Joice" ]
> 
> console.log(" Utilizando o Comando de repetição FOR ")
> console.log("")
> 
> for (let indice = 0; indice < nomes.length; indice++) {
>     posicao = indice + 1
>     console.log("Nome " + posicao + ": " + nomes[indice]);
> 
> }
> console.log("")
> indice = 0
> console.log(" Utilizando o comando de Repetição While ")
> console.log("")
> while (indice < nomes.length) {
>     posicao = indice + 1
>     console.log("Nome " + posicao + ": " + nomes[indice])
>     console indice ++ 
> } 
> . log ( "" )
> 
> 
> console.log("")
> indice = 0
> console.log(" Utilizando o comando de Repetição  Do While ")
> console.log("")
> do {
>     posicao = indice + 1
>     console.log("Nome " + posicao + ": " + nomes[indice])
>     indice++
> }
> while (indice < nomes.length) {}
> console.log("")
> console.log("Fim do Exercício 1")
> console.log("")
> 
> console.log("Aula 08 - Exercício 2")
> console.log("")
> console.log("Crie um algoritmo capaz de calcular a média aritmética de um array com qualquer quantidade")
> console.log("de elementos numéricos. Para fins de exemplo, o resultado do algoritmo com um array de valores 1, 2, 3, 5, 8, 13, 21, 23, 34, 55 deve ser 16.5.")
> console.log("Procure usar uma estrutura de repetição diferente da que você usou para fazer o exercício anterior;")
> console.log("")
> 
> //Declarações
> 
> numeros = [55, 27, 39, 52, 8, 13, 21, 23, 34, 55]
> tamanhoDeNumeros = numeros.length
> soma = 0
> media = 0
> 
> 
> console.log(" Apresentaremos a média aritmétida de " + tamanhoDeNumeros + " números.")
> console.log("Os números são: " + numeros)
> console.log("")
> 
> //Execução de comandos de repetição
> console.log("Executando com For")
> 
> for (indice = 0; indice < numeros.length; indice++) {
> 
>     soma = numeros[indice] + soma
>     media = soma / tamanhoDeNumeros
> }
> console.log(" A média entre os números é: " + media.toFixed(2) + ".")
> console.log("")
> 
> console.log("Executando com While")
> 
> while  ( índice  <  numeros . comprimento )  {
> 
>     soma = numeros[indice] + soma
>     media = soma / tamanhoDeNumeros
>     indice++
> 
> }
> console.log(" A média entre os números é: " + media.toFixed(2) + ".")
> console.log("")
> 
> console.log("Executando com Do... While")
>     //zerando as variáveis
> 
> índice  =  0 
> soma  =  0 
> média  =  0
> 
> 
> do {
>     soma = numeros[indice] + soma
>     media = soma / numeros.length
>     indice++
> 
> }
> while (indice < numeros.length)
> console.log(" A média dos números é: " + media.toFixed(2) + ".")
> console.log("")
> console.log("Fim do Exercício 2")
> console.log("")
>     //--------------------------------------------------------------
> 
> console.log("Aula 08 - Exercício 3")
> console.log("")
> console.log("Considerando a lista dos 60 nomes mais comuns no Brasil nos últimos 10 anos, crie um algoritmo para verificar se seu nome está lá.")
> console.log("Se sim, exiba a mensagem: É, nome comum :P. Se não, exiba a mensagem: Diferentão, hein? XD.")
> 
> console.log(" Utilizando o Comando de repetição FOR ")
> console.log("")
>     // Declaração das variáveis
> 
> nomesMaisComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia",
>     "Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia",
>     "Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina",
>     "Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia",
>     "Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda",
>     "Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"
> ]
> nome = "Lorena"
> index = 0
> nomeComum = false
> tamanhoNomes = nomesMaisComuns.length
> 
> 
> //Execução
> 
> 
> 
> for (index = 0; index < nomesMaisComuns.length; index++) {
> 
>     if (nome == nomesMaisComuns[index]) {
>         nomeComum = true
>         break
> 
>     }
> }
> 
> if (nomeComum) {
>     console.log(" O nome que seus pais lhe deram " + nome + " é comum. :P ")
> } else
>     console.log("O nome que seus pais lhe deram " + nome + " é diferentão hein! XD")
> console.log("Fim do  FOR -- |For funcionando")
> console.log("")
> 
> 
> 
> console.log("Utilizando o comando de repetição While")
> console.log("")
> 
> //Declaração das Variáveis
> meuNome = "Joelma"
> index = 0
> nomeComum1 = false
> 
> //Execução
> while (index < nomesMaisComuns.length) {
>     if (meuNome == nomesMaisComuns[index]) {
>         nomeComum1 = true
>         break
>     }
>     index++
> 
> }
> if (nomeComum1) {
>     console.log(" O nome que seus pais lhe deram " + meuNome + " é comum. :P ")
> } else
>     console.log("O nome que seus pais lhe deram " + meuNome + " é diferentão hein! XD")
> console.log("Fim do  WHILE *While Funcionando*")
> console.log("")
> 
> 
> 
> console.log(" Utilizando o Comando de repetição DO... WHILE ")
> console.log("")
>     // declaração de  variáveis
> nomeMeu = "Jojo"
> index = 0
> nomeComum2 = false
> 
> 
> do {
>     if (nomeMeu == nomesMaisComuns[index]) {
>         nomeComum2 = true
>         break
>     }
>     index++
> 
> } while (index < nomesMaisComuns.length);
> 
> switch (nomeComum2) {
>     case true:
>         console.log(" O nome que seus pais lhe deram " + nomeMeu + " é comum. :P ")
>         break
>     case false:
>         console.log("O nome que seus pais lhe deram " + nomeMeu + " é diferentão hein! XD")
>         break
> }
> console.log("Fim do comando DO... WHILE * DO..While Funcionando*")
> console.log( "" )
> 
> //FIM DOS EXERCÍCIOS DE COMANDO DE REPETIÇÃO>
> `
> ```
Olá tudo certo? espero que sim, primeiro parabéns por conseguir fazer os exercícios, legal ver o avanços de vocês  mas se me permite vou dar um pitaco no seu código:

na parte dos comandos de repetição:

````javascript

//Execução de comandos de repetição

  for (indice = 0; indice < numeros.length; indice++) {
  
      soma = numeros[indice] + soma
      media = soma / tamanhoDeNumeros           // calculo repetido
  }

````
Uma pequena observação, note que para cada vez que o código de repetição é executado o calculo da media é refeito, e no final e exibido somente o ultimo calculo? então isso não ocasiona problemas no resultado final desse código, mas pode trazer problemas de performance, tendo em vista que toda vez ele vai fazer um calculo que poderia ser feito só uma vez, talvez aqui em pequenas contas e com um array de números pequenos não se note tanto, mas caso a quantidade de números aumente no array, já se notaria pequenas diferenças na execução.

Algo como exemplo abaixo já melhora a performance, evitando cálculos repetidos  


````javascript

//Execução de comandos de repetição
  
  soma  =  0 
  for (indice = 0; indice < numeros.length; indice++) {  
      soma = numeros[indice] + soma
  }
  // validação para ver se a soma é maior que 0, isso indica que entrou no repetidor e evita o erro de calculo
  if(soma > 0){
        media = soma / tamanhoDeNumeros           // calcular depois
  }else{
       media  = 0;
  }
}

````

Mas volto a parabenizar pela dedicação, bons estudos e espero ter conseguido passar minha mensagem.

Attt
