### ISSUE TITLE
Aula 08 - Exercício número 3 - Compartilhando resolução alternativa

### ISSUE THREAD

**Issue by matheus-diefenthaeler** [cwi-reset/edicao-02-qualificatoria#18]
Fala pessoal boa noite!

Apenas compartilhando uma resolução alternativa.

Utilizando o método **indexOf()** cujo mesmo retorna o primeiro índice em que o elemento pode ser encontrado dentro de um array, retornando -1 caso o mesmo não seja encontrado.

```javascript
//Aula_08 - Exercício 03
nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia", 
"Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia", 
"Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina", 
"Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia", 
"Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda", 
"Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"];

if(nomesComuns.indexOf("Matheus") === -1){
    console.log("Diferentão, hein? xD");
}else{
    console.log("É, nome comum :P");
}
```

**Comment by AlexandreSNeto** [comment]
Boa @matheus-diefenthaeler!

A maioria das linguagens possui a funcionalidade do `indexOf`, porém optamos pela solução usando `for` para ser agnóstica à linguagem (neste caso, JavaScript) e também para fazer uso da estrutura de repetição. 😁

Mas a tua solução é válida e isso mostra como podemos ter várias soluções para um mesmo problema.

**Comment by matheus-diefenthaeler** [comment]
@AlexandreSNeto Entendido! 😅😅

**Comment by MTheobald86** [comment]
Obrigado por apresentar a alternativa @matheus-diefenthaeler ! Achei interessante!
Abraço!

**Comment by Lorandi** [comment]
Muito bom. Não conhecia o método **indexOf()**. Valeu por compartilhar

**Comment by GuiMichel** [comment]
Faala Rapeize!
Muito legal ver as diversar formas de resolução!

Segue a minha para vocês.

`nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia", 
"Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia", 
"Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina", 
"Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia", 
"Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda", 
"Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"];

for(i=0;i<nomesComuns.length;i++){
  if(nomesComuns[i]== "Guilherme"){
    console.log("É, nome comum :P");
    break;
  }else if (i== nomesComuns.length-1){
    console.log("Diferentão, hein? XD");
    break;
  }
}
`
flws!

**Comment by elciodalosto** [comment]
@GuiMichel eu também utilizei o break! 
Eu estava me achando muito estranho por estar usando isso, aí vi teu código, não me sinto mais tão fora de contexto kkkkk
dahora ver as semelhanças e diferenças na hora de montar o código

nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia", 
"Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia", 
"Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina", 
"Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia", 
"Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda", 
"Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]

for(i=0; i<nomesComuns.length; i++){
  if(nomesComuns[i] == "Elcio"){
    console.log("É, nome comum :P.")
    break
  }else
    console.log("Diferentão, hein? XD.")
    break
}

**Comment by elciodalosto** [comment]
@GuiMichel eu também utilizei o break!

Eu estava me achando muito estranho por estar usando isso, aí vi teu código, não me sinto mais tão fora de contexto kkkkk
dahora ver as semelhanças e diferenças na hora de montar o código. 

Só estou me batendo pra fazer o código ficar estilizado, indentado e colorido... eu abro o "insert code" ali mas nada acontece.. apenas adiciona um acento de crase antes e depois do código e não estiliza... já deletei e recomentei e não resolve...


`nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia",
"Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia",
"Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina",
"Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia",
"Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda",
"Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]

for(i=0; i<nomesComuns.length; i++){
  if(nomesComuns[i] == "Elcio"){
  console.log("É, nome comum :P.")
  break
}else
console.log("Diferentão, hein? XD.")
break
}`

**Comment by GuiMichel** [comment]
> @GuiMichel eu também utilizei o break!
> 
> Eu estava me achando muito estranho por estar usando isso, aí vi teu código, não me sinto mais tão fora de contexto kkkkk
> dahora ver as semelhanças e diferenças na hora de montar o código.
> 
> Só estou me batendo pra fazer o código ficar estilizado, indentado e colorido... eu abro o "insert code" ali mas nada acontece.. apenas adiciona um acento de crase antes e depois do código e não estiliza... já deletei e recomentei e não resolve...
> 
> `nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia",
> "Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia",
> "Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina",
> "Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia",
> "Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda",
> "Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]
> 
> for(i=0; i<nomesComuns.length; i++){
> if(nomesComuns[i] == "Elcio"){
> console.log("É, nome comum :P.")
> break
> }else
> console.log("Diferentão, hein? XD.")
> break
> }`

Fala @elciodalosto eu aprendi essa função de inserir código hoje com o  @gilvangobbato, na minha primeira edição ele demorou para atualizar e ficar bonitinho.... pode ser isso.

a respeito do break achei interessante pois assim ele para de procurar se achar no início da pesquisa 👌🏼 .

**Comment by GuiMichel** [comment]
> Fala pessoal boa noite!
> 
> Apenas compartilhando uma resolução alternativa.
> 
> Utilizando o método **indexOf()** cujo mesmo retorna o primeiro índice em que o elemento pode ser encontrado dentro de um array, retornando -1 caso o mesmo não seja encontrado.
> 
> ```js
> //Aula_08 - Exercício 03
> nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia", 
> "Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia", 
> "Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina", 
> "Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia", 
> "Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda", 
> "Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"];
> 
> if(nomesComuns.indexOf("Matheus") === -1){
>     console.log("Diferentão, hein? xD");
> }else{
>     console.log("É, nome comum :P");
> }
> ```

Massa demais esse resolução!

**Comment by FelipeLT** [comment]
Fala ai turma, belê... 
Bacana a contribuição de vcs com as soluções alternativas... show... ajuda muito.

@elciodalosto 
Eu tentei rodar o teu código com o meu nome mas a condição não respondeu corretamente... será q estou fazendo algo errado?   

for (index=0; index < nomesComuns.length; index++) {
if (nomesComuns[index] == "Felipe") {
console.log("É, nome comum :P.");
break;
} else {
console.log("Diferentão, hein? XD.");
break;
}
}

**Comment by AlexandreSNeto** [comment]
@elciodalosto e @FelipeLT 

A solução proposta pelo @elciodalosto possui um erro de lógica e um erro de sintaxe. Por isso o @FelipeLT não conseguiu testar um nome que é comum.

Vamos analisar inicialmente o código do @elciodalosto:
```javascript
for(i=0; i<nomesComuns.length; i++){
  if(nomesComuns[i] == "Elcio"){
      console.log("É, nome comum :P.")
      break
    }else
        console.log("Diferentão, hein? XD.")
    break
}
```

O erro de sintaxe está no `else`.  Percebam que o bloco de código não possui os delimitadores `{` e `}`. Esse é um erro bastante comum. Os comandos `if` e `else` podem ou não ser delimitados por `{` e `}`. Quando não forem delimitados dessa forma, somente o comando imediatamente posterior ao `if` ou `else` será considerado. Com isso, o bloco considerado pelo `else` é somente o `console.log("Diferentão, hein? XD.")`.

Para corrigir, basta incluir os 2 comandos dentro dos delimitadores `{` e `}`. Ficando assim:

```javascript
for (index=0; index < nomesComuns.length; index++) {
    if (nomesComuns[index] == "Felipe") {
        console.log("É, nome comum :P.");
        break;
    } else {
        console.log("Diferentão, hein? XD.");
        break;
    }
}
```

Mas isso ainda não corrige o problema reportado pelo @FelipeLT. Inclusive, o código acima é exatamente o mesmo postado por ele. Ao executar o exercício usando o nome "Felipe", que consta no array como um nome comum, recebemos o retorno "Diferentão, hein? XD.", quando o esperado era "É, nome comum :P.".

Vamos tentar analisar o código por partes, para identificar onde está o defeito. Vou incluir um `console.log(index)` para entender quantas vezes o trecho de código do `for` é executado:

```javascript
for (index = 0; index < nomesComuns.length; index++) {
  console.log(index)
  if (nomesComuns[index] == "Felipe") {
    console.log("É, nome comum :P.");
    break;
  } else {
    console.log("Diferentão, hein? XD.");
    break;
  }
}
```

A saída do programa ficou assim:
```
0
Diferentão, hein? XD.
```

Ou seja, o `for` foi executado somente 1 vez. Lembrando que o array está dessa forma:
```javascript
nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia",
  "Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia",
  "Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina",
  "Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia",
  "Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda",
  "Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]
```

Como o `for` foi executado somente 1 vez, somente o nome "Miguel" foi testado no `if`. Obviamente, "Miguel" é diferente de "Felipe", portanto o código vai cair no `else`. Lembrando que ele possui 2 comandos:
```javascript
else {
    console.log("Diferentão, hein? XD.");
    break;
  }
```

O primeiro comando foi executado, tanto que vemos na saída o texto "Diferentão, hein? XD.". E logo o segundo comando, o `break` também é executado. O problema é que o `break` encerra o `for`. Então nenhum outro nome é testado e a aplicação encerra.

Se removermos o `break`, já teremos um avanço. Vejam como ficou o código e a saída:
```javascript 
for (index = 0; index < nomesComuns.length; index++) {
  console.log(index)
  if (nomesComuns[index] == "Felipe") {
    console.log("É, nome comum :P.");
    break;
  } else {
    console.log("Diferentão, hein? XD.");
    //break;
  }
}
```

Saída:
```
0
Diferentão, hein? XD.
1
Diferentão, hein? XD.
2
Diferentão, hein? XD.
3
Diferentão, hein? XD.
4
Diferentão, hein? XD.
5
Diferentão, hein? XD.
6
Diferentão, hein? XD.
7
Diferentão, hein? XD.
8
Diferentão, hein? XD.
9
Diferentão, hein? XD.
10
Diferentão, hein? XD.
11
Diferentão, hein? XD.
12
Diferentão, hein? XD.
13
Diferentão, hein? XD.
14
Diferentão, hein? XD.
15
Diferentão, hein? XD.
16
Diferentão, hein? XD.
17
Diferentão, hein? XD.
18
Diferentão, hein? XD.
19
Diferentão, hein? XD.
20
Diferentão, hein? XD.
21
Diferentão, hein? XD.
22
Diferentão, hein? XD.
23
Diferentão, hein? XD.
24
Diferentão, hein? XD.
25
Diferentão, hein? XD.
26
Diferentão, hein? XD.
27
Diferentão, hein? XD.
28
Diferentão, hein? XD.
29
Diferentão, hein? XD.
30
Diferentão, hein? XD.
31
Diferentão, hein? XD.
32
Diferentão, hein? XD.
33
Diferentão, hein? XD.
34
É, nome comum :P.
```

Eeeeita. Temos um problema aqui né ?

Bom, como removemos o `break`, agora a aplicação está testando todos os nomes e parou quando encontrou o "Felipe" lá no array. Mas não queremos que o programa exiba o outro texto para os nomes que não coincidem.

Aqui chegamos no problema de lógica.

Temos algumas formas de resolver este problema. Vou deixar algumas sugestões, que inclusive já foram dadas por outros colegas:

Sugestão do @GuiMichel 
```javascript
for (index = 0; index < nomesComuns.length; index++) {
  if (nomesComuns[index] == "Felipe") {
    console.log("É, nome comum :P.");
    break;
  } else if (index == nomesComuns.length-1) { 
    // Verifica se o indice que está sendo testado é o último do array. Se for, significa que não encontou o nome no array, então pode imprimir que o nome é diferentão
    console.log("Diferentão, hein? XD");
    break;
  }
}
```

Sugestão do @matheus-diefenthaeler:
```javascript
// O comando "indexOf" tenta obter o index do array que possui o valor passado por parâmetro. Caso encontre, será retornado o índice do array. Caso contrário, será retornado "-1". Dessa forma, não é necessário percorrer todo o array para tentar encontrar o nome
if(nomesComuns.indexOf("Felipe") === -1){
    console.log("Diferentão, hein? xD");
}else{
    console.log("É, nome comum :P");
}
```

Minha sugestão, ainda usando `for` (que era o objetivo do exercício):
```javascript
// Crio uma variável para identificar se foi encontrado o nome dentro do array
encontrou = false
for (index = 0; index < nomesComuns.length; index++) {
  // Testo apenas se encontrou o valor
  if (nomesComuns[index] == "Felipe") {
    // Se encontrou, altera o valor da minha variável de controle
    encontrou = true
    // Executa o break, pois não preciso mais continuar percorrendo o array
    break;
  }
}
// Ao final da execução, verifica se encontrou e exibe a mensagem de acordo com o resultado
if (encontrou) {
  console.log("É, nome comum :P.")
} else {
  console.log("Diferentão, hein? XD.")
}
```

Importante ressaltar que não existe maneira correta de fazer, desde que o objetivo seja cumprido. O código do @elciodalosto possuia um erro. Dependendo da maneira que fosse testado, esse erro não fica evidente. Por isso é importante testar o código com vários valores diferentes.

Desculpem o mural! Mas achei importante tentar explicar tudo.

Bons estudos galera 🚀

**Comment by gsvarriale** [comment]
Segue a minha versão:
```javascript
// Exercício 3: Considerando a lista dos 60 nomes mais comuns no Brasil nos últimos 10 anos, crie um algoritmo para verificar se seu nome está lá. Se sim, exiba a mensagem: É, nome comum :P. Se não, exiba a mensagem: Diferentão, hein? XD.
nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia", 
"Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia", 
"Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina", 
"Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia", 
"Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda", 
"Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"];

nomeConsultado = "Thiago";
resultado = false;

for (i=0; i<nomesComuns.length; i++) {
	if (nomesComuns[i] == nomeConsultado) {
		resultado = true;
	}
}

if (resultado == true) {
	console.log("É, nome comum :P");
} else {
	console.log("Diferentão, hein? XD");
}
```
[]'s

**Comment by thaisbg** [comment]
Estava revisando os exercícios e vim ver essa issue pra ver outras possibilidades de resolução, realmente é bem interessante ver a variedade alternativas para resolver um mesmo problema. @matheus-diefenthaeler, obrigada por compartilhar conosco o indexOf() :D
Na minha versão mantive o if dentro do laço mesmo, e criei uma nova variável pra armazenar a mensagem (evitando que o resultado fosse impresso a cada iteração).
 
```javascript
nome = "Maria"
nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia", 
"Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia", 
"Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina", 
"Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia", 
"Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda", 
"Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]
mensagem = ""

for (i = 0; i < nomesComuns.length; i++) {
    if (nomesComuns[i] == nome) {
        mensagem = "É, nome comum :P"
        break
    } else {
        mensagem = "Diferentão, hein? XD"
    }
}

console.log(mensagem)
```
