### ISSUE TITLE
Contato - LinkedIn, etc...

### ISSUE THREAD

**Issue by JoseaneGrigolo** [cwi-reset/edicao-02-qualificatoria#20]
Oi Galerinha, 
Criei este para quem quiser me add e/ou incluir o seu LinkedIn para contato.
>>> https://www.linkedin.com/in/joseane-ivelise-grigolo-863a1a35
👍

**Comment by FernandoSSilvano** [comment]
https://www.linkedin.com/in/fernando-silvano-0b61a8193/
Segue meu linkedin para quem quiser também.

**Comment by coutomariel** [comment]
https://www.linkedin.com/in/coutomariel/
Meu linkedin, network é vida.

**Comment by LFPires1993** [comment]
Só chamar pessoal, uma rede bem estruturada pode fazer diferença em alguns momentos 💪💪

https://www.linkedin.com/in/lucaspires-ti

**Comment by Lorandi** [comment]
Boa. Bora conectar. [www.linkedin.com/in/rodrigo-lorandi](url)

**Comment by denicomaru** [comment]
Oi pessoal tudo bem? 
Quem quiser entrar em contato pelo LinkedIn: https://www.linkedin.com/in/denisecomar%C3%BA/

**Comment by MTheobald86** [comment]
www.linkedin.com/in/maycon-theobald-37b08412a

**Comment by AlexsonT** [comment]
https://www.linkedin.com/in/alexson-theobald-a6a56958/

**Comment by rss-resouza** [comment]
Segue o meu
linkedin.com/in/rss-re-souza

**Comment by lucaslinsbaia** [comment]
Este é o meu https://www.linkedin.com/in/lucaslinsbaia/

**Comment by GiuseppeVarriale** [comment]
Boa! Esse é o meu
[Linkedin](https://www.linkedin.com/in/giuseppe-varriale86)

**Comment by csdamo** [comment]
[www.linkedin.com/in/cristiane-damo-20ab34b8](url)

**Comment by SandroM3llo** [comment]
inkedin.com/in/sandrom3llo

**Comment by SandroM3llo** [comment]
[https://www.linkedin.com/in/sandrom3llo/](url)

**Comment by SandroM3llo** [comment]
https://www.linkedin.com/in/sandrom3llo/

**Comment by wirthgabriele** [comment]
linkedin.com/in/gabriele-wirth-b7a11916

**Comment by wirthgabriele** [comment]
https://www.linkedin.com/in/gabriele-wirth-b7a11916/

**Comment by AnaBirk** [comment]
Oii, meu perfil do Linkedin:
https://www.linkedin.com/in/anabirk/

**Comment by AlexandreSNeto** [comment]
http://linkedin.com/in/alexandresilveiraneto

**Comment by gilvangobbato** [comment]
https://www.linkedin.com/in/gilvangobbato/

**Comment by Lucas-Bavaresco** [comment]
https://www.linkedin.com/in/lucas-bavaresco/

**Comment by eloschwertner** [comment]
https://www.linkedin.com/in/eloisa-schwertner-a96a38b9/
