### ISSUE TITLE
Aula 04

### ISSUE THREAD

**Issue by Meli2203** [cwi-reset/edicao-02-qualificatoria#22]
Boa tarde! Na aula 04, a apresentação que pediram para montarmos, lá no me completo e etc,
., como sei quando devo colocar entre "", tipo: nomeCompleto: "Melissa Cunha", apelido "Meli" e quando não colocar?

**Comment by RafaelStefaniBaptista** [comment]
Oii boa tarde Melissa,

Como foi explicado na aula o valor das variaveis do tipo `string` é definido entre aspas duplas ("), é assim que conseguimos definir um texto nas linguagens de programação, como por exemplo:

```javascript
texto = "Este é um teto de exemplo"
console.log(texto)
```
Como tu pode observar temos também o uso do operador mais (+), que tem função de juntar o texto com outro texto ou variavel, como por exemplo:

```javascript
numero = 2
texto = "O Número é " + numero
console.log(texto)
```
O que esta sendo pedido é simplesmente para criar as variaveis usadas no texto como neste ultimo exemplo.

Me fiz claro?

Qualquer duvida pode questionar 😄

**Comment by CarlosBueno3000** [comment]
Complementando, te imagina escrevendo o comando de impressão, em vários pontos tu vai precisar escrever entre "", pois são os textos que tu queres mostrar na tela.

Em alguns, vai ter de colocar um espaço após a última palavra, para o texto final, em tela não ficar colado. Pega o exemplo de antes: 

numero = 2
texto = "O Número é " + numero
console.log(texto)

Se não der aquele espacinho depois do "é", acaba saindo tudo junto: O número é2  o que pode parecer estranho.

Para mim, fica mais fácil sempre colocar um espaço após cada trecho, pois consigo visualizar melhor o que estou escrevendo, mesmo que os sistemas não façam distinção se tem ou não um espaço....

**Comment by Meli2203** [comment]
Obrigada!!!
________________________________
De: Carlos Alexandre Bueno <notifications@github.com>
Enviado: terça-feira, 29 de dezembro de 2020 23:39
Para: cwi-reset/edicao-02-qualificatoria <edicao-02-qualificatoria@noreply.github.com>
Cc: Melissa <melissancunha@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [cwi-reset/edicao-02-qualificatoria] Aula 04 (#22)


Complementando, te imagina escrevendo o comando de impressão, em vários pontos tu vai precisar escrever entre "", pois são os textos que tu queres mostrar na tela.

Em alguns, vai ter de colocar um espaço após a última palavra, para o texto final, em tela não ficar colado. Pega o exemplo de antes:

numero = 2
texto = "O Número é " + numero
console.log(texto)

Se não der aquele espacinho depois do "é", acaba saindo tudo junto: O número é2 o que pode parecer estranho.

Para mim, fica mais fácil sempre colocar um espaço após cada trecho, pois consigo visualizar melhor o que estou escrevendo, mesmo que os sistemas não façam distinção se tem ou não um espaço....

**Comment by DiegoReset21** [comment]
Olá Melissa!

No JavaScript você pode utilizar tanto aspas simples ( ' ) ou aspas duplas ( " ) ambas serão atribuídas como String.

Já quanto ao uso ( = ), uma outra forma de entender, é ler como recebe, ao invés de igual somente uma dica...👍

**Comment by AlexandreSNeto** [comment]
> Olá Melissa!
> 
> No JavaScript você pode utilizar tanto aspas simples ( ' ) ou aspas duplas ( " ) ambas serão atribuídas como String.
> 
> Já quanto ao uso ( = ), uma outra forma de entender, é ler como recebe, ao invés de igual somente uma dica...👍

Boa @DiegoReset21!

Quando falamos exclusivamente do JavaScript, de fato podemos entender que tanto aspas simples quanto duplas são Strings. 
Porém em outras linguagens, como o Java, isso não é verdade. 

Mas esse é um assunto para o treinamento.

Vale reforçar também que o "tipo" do dado influencia na forma com que definimos o valor de uma variável.

Ex:
```javascript
nomeCompleto = "Alexandre Silveira"
idade = 33
possuiGitHub = true
```

Percebam que para Strings eu usei aspas duplas (neste caso, poderia ser simples também). Mas para idade, que eu quero atribuir como um número, eu não usei as aspas. O mesmo aconteceu para o tipo `boolean`, onde usei `true` sem aspas.

Se analisarmos o seguinte exemplo:
```javascript
nomeCompleto = "Alexandre Silveira"
idade = "33"
possuiGitHub = "true"
```
O JavaScript vai aceitar as declarações, porém não vai entender que a variável `idade` é um número, mas sim um texto (String) que possui o valor "33". O mesmo para variável `possuiGitHub`, que vai ser um texto com o valor "true" e não uma variável booleana de fato.

**Comment by Meli2203** [comment]
Obrigada gente!

**Comment by MoraesJorge** [comment]
Apenas acrescentaria que a junção (ou aglutinação, se preferir) de strings se chama _concatenar_.
Vlw pessoal!

**Comment by nand-up** [comment]
Oi, pessoal! 
Minha questão tem a ver com a variável do tipo "lógico".

Embora eu escreva o código exatamente como o descrito no exemplo, ele não reconhece como verdadeiro o termo "desempregada". O que será que pode estar dando errado? 

Outro detalhe que observei depois de conferir a resposta, foi que ao final de cada construção, digitei a referência console.log = conforme os exemplos do vídeo: 

apelido = "Fécula";
console.log = apelido

No entanto, vi na resposta que não foi necessário incluir a referência todas as vezes. Testei aqui no Repl.it e deu certo com e sem. Gostaria de saber se a inclusão foi utilizada apenas para fins pedagógicos ou se teria alguma outra razão.

Obrigada! :)

**Comment by IaraBarbosa** [comment]
Oi, Fernanda!

É literalmente como se fosse feita uma pergunta. 
expressão ? verdadeiro : falso
Caso a resposta seja verdadeira, é retornado o primeiro valor, caso falsa, o segundo. 

Seguindo seu exemplo 
Não estou trabalhando, logo:
trabalhando = false

Assim a expressão booleana trará a resposta da pergunta:
trabalhando ? "empregado" : "desempregado"

**Comment by nand-up** [comment]
Muito obrigada pelo retorno, Iara! :)

Revendo aqui, tinha feito do modo correto, mas coloquei false entre aspas. Como a impressão não acusou nenhum erro de sintaxe, pensei que pudesse ter errado em outra coisa.

**Comment by Lorandi** [comment]
Isso é super comum. Já me aconteceu de ficar um tempão quebrando cabeça e o que faltava (ou sobrava) era um **'** , **;** ou **}**
