### ISSUE TITLE
último exercício

### ISSUE THREAD

**Issue by Meli2203** [cwi-reset/edicao-02-qualificatoria#23]
Galera, pode parecer perguntas bobas para vocês (risos), mas realmente estão me surgindo.

No exemplo do boleto com juros, consegui fazer. Porém, nas primeiras tentativas estava colocando R$ e deu erro.
Se fizermos sem o cifrão, o sistema irá entender depois que precisa colocá-lo na hora de gerar o boleto?

**Comment by AlexandreSNeto** [comment]
@Meli2203 Só pra confirmar, vc está falando da aula 5, certo ?

**Comment by AlexandreSNeto** [comment]
Bom vamos lá. 

Primeiramente, tua dúvida não é boba. Faz bastante sentido!

Nos exercícios, tentamos sempre trazer o mais próximo da vida real. Se estivéssemos trabalhando em um banco ou financeira e precisássemos implementar um gerador de boletos, a área de negócios usaria exemplos com "R$" para representar os valores monetários.

Porém, sistemicamente falando, nós não representamos a moeda diretamente no código. Para o código, não importa se um número é um valor em reais ou se é o número de uma casa. Tudo são números.

O que vai definir isso, é o contexto da aplicação. No nosso caso, estamos falando de valores monetários e boletos. Então os números devem ser representados por uma moeda. Seja "R$" para o Brasil ou "US$" para os Estados Unidos por exemplo. Mas vamos fazer isso somente na hora de apresentar o resultado para o usuário.

Vamos para um exemplo:
```javascript
valorBoleto = 150.0
valorComJuros = (valorBoleto * 1.1)
console.log("O valor atualizado do boleto é R$ " + valorComJuros)
```

Perceba que eu usei o valor `150.0` para definir o valor inicial do boleto, mas usei o "R$" dentro do texto que vou apresentar para o usuário da aplicação.

Claro que aqui estamos fazendo exercícios simples, a "apresentação" nada mais é do que um texto simples. Mas se imaginarmos o aplicativo de internet Banking que usamos bastante, por baixo dos panos ele está calculando tudo com números e só na hora de montar a tela para o usuário é que ele transforma aquele valor adicionando a moeda na frente.

Então resumindo, no código nós nunca usamos a representação de moeda, usamos apenas os números. 

Se restar alguma dúvida, fica a vontade para seguir perguntando.

**Comment by Macenab** [comment]
Boa tarde! 

Acho que sua dúvida seria algo como colocar o "R$" na variável, e o console mostrar o valor juntamente com a identificação da moeda Real, algo como "R$ xxx,xx", correto?

Caso seja isso, variáveis não aceitam caracteres especiais, nem no inicio ou no fim!

Para que apareça no console, você pode usar a Concatenação de valores(variáveis/Strings etc), direto no comando de impressão, algo como esse exemplo:

`console.log("R$: " + valorJuros)`

Com isso o console mostrará o cifrão + o valor como utilizamos no nosso dia a dia! Caso for uma situação diferente, complemente sua dúvida e tentaremos ajuda-lá. (Lembrando, nenhuma dúvida é bobagem, pode perguntar à vontade)

**Comment by GuiMichel** [comment]
Segue minhas soluções para comparação!

// Aula 05.06
// let saldo = 1000.00;

// saldo = saldo - 99.9;
// saldo = saldo + 2500;
// saldo = saldo - 0.1;
// saldo = saldo - (saldo*0.25);
// saldo = saldo - (saldo/2);

// console.log("Seu saldo é de "+saldo.toFixed(2)+" R$.");




// Aula 05.05
// let custoProdutos = 500;
// let receitaLiquida = 1000;
// let lucroBruto = receitaLiquida - custoProdutos;

// let margemBruta = (lucroBruto/receitaLiquida)*100;
// console.log("A margem bruta é de " +margemBruta+"%.");

// Aula 05.04
// let item1 = 2;
// let item2 = 2;
// let item3 = 2;
// let item4 = 2;
// let item5 = 2;
// let mediaAritmetica = 0;

// mediaAritmetica = (item1+item2+item3+item4+item5)/5;

// console.log(mediaAritmetica);


// Aula 05.03

// let boleto = 100.00;
// let juros = 0.1;
// let valorComJuros = 0;

// valorComJuros = boleto + (boleto*juros);

// console.log(valorComJuros);

// Aula 05.02
// let idade = 30;
// let maiorIdade = "true";

// maiorIdade = idade>=18;


// Aula 05.01

// let nomeDoFulano = "Fulano";
// let nomeDoCiclano = "Ciclano";

// mesmoNome = nomeDoFulano == nomeDoCiclano;

**Comment by Lorandi** [comment]
A minha ficou assim:

```
// let idade = 5;
nomeDoFulano = "Pedro";
nomeDoBeltrano = "João";

mesmoNome  = (nomeDoFulano == nomeDoBeltrano )

console.log(mesmoNome)



valor = 100

valorComJuros = valor + (valor*0.1)

console.log(valorComJuros)


item1 = 10;
item2 = 20;
item3 = 30; 
item4 = 40;
item5 = 50;

console.log((item1+item2+item3+item4+item5)/5)

//lucroBruto = receitaLiquida - custoProdutos

//margemBruta = (lucroBruto/receitaLiquida)*100


saldoInicial = 1000

calça = 99.90

salario = 2500

doacao = 0.1000

saldoAtual = saldoInicial - calça + salario - doacao 

arCondicionado = saldoAtual * 0.2500

saldoAtual = saldoAtual - arCondicionado 

divida = saldoAtual * 0.50

saldoAtual = saldoAtual - divida

console.log("O saldo atual é R$",saldoAtual.toFixed(2))
```

**Comment by AlexandreSNeto** [comment]
> Segue minhas soluções para comparação!
> 
> // Aula 05.06
> // let saldo = 1000.00;
> 
> // saldo = saldo - 99.9;
> // saldo = saldo + 2500;
> // saldo = saldo - 0.1;
> // saldo = saldo - (saldo*0.25);
> // saldo = saldo - (saldo/2);
> 
> // console.log("Seu saldo é de "+saldo.toFixed(2)+" R$.");
> 
> // Aula 05.05
> // let custoProdutos = 500;
> // let receitaLiquida = 1000;
> // let lucroBruto = receitaLiquida - custoProdutos;
> 
> // let margemBruta = (lucroBruto/receitaLiquida)*100;
> // console.log("A margem bruta é de " +margemBruta+"%.");
> 
> // Aula 05.04
> // let item1 = 2;
> // let item2 = 2;
> // let item3 = 2;
> // let item4 = 2;
> // let item5 = 2;
> // let mediaAritmetica = 0;
> 
> // mediaAritmetica = (item1+item2+item3+item4+item5)/5;
> 
> // console.log(mediaAritmetica);
> 
> // Aula 05.03
> 
> // let boleto = 100.00;
> // let juros = 0.1;
> // let valorComJuros = 0;
> 
> // valorComJuros = boleto + (boleto*juros);
> 
> // console.log(valorComJuros);
> 
> // Aula 05.02
> // let idade = 30;
> // let maiorIdade = "true";
> 
> // maiorIdade = idade>=18;
> 
> // Aula 05.01
> 
> // let nomeDoFulano = "Fulano";
> // let nomeDoCiclano = "Ciclano";
> 
> // mesmoNome = nomeDoFulano == nomeDoCiclano;

@GuiMichel Não existe  nenhum erro na tua solução, porém vale um comentário:

Não há necessidade de declarar cada variável que tu for usar. Por exemplo, no exercício 05.02 vc não precisa iniciar a variável `maiorIdade`. Inclusive, a maneira que vc iniciou está incorreta, pois não usamos aspas em tipos booleanos. O correto seria `maiorIdade = true` (sem aspas). Não deu nenhum problema pois o JavaScript não tem tipagem forte, ou seja, uma variável pode assumir vários tipos no decorrer do código. No teu caso, ela iniciou sendo uma String com o valor "true" e depois virou um valor boolean do resultado da expressão `idade >= 18`.

**Comment by AlexandreSNeto** [comment]
> A minha ficou assim:
> 
> ```
> // let idade = 5;
> nomeDoFulano = "Pedro";
> nomeDoBeltrano = "João";
> 
> mesmoNome  = (nomeDoFulano == nomeDoBeltrano )
> 
> console.log(mesmoNome)
> 
> 
> 
> valor = 100
> 
> valorComJuros = valor + (valor*0.1)
> 
> console.log(valorComJuros)
> 
> 
> item1 = 10;
> item2 = 20;
> item3 = 30; 
> item4 = 40;
> item5 = 50;
> 
> console.log((item1+item2+item3+item4+item5)/5)
> 
> //lucroBruto = receitaLiquida - custoProdutos
> 
> //margemBruta = (lucroBruto/receitaLiquida)*100
> 
> 
> saldoInicial = 1000
> 
> calça = 99.90
> 
> salario = 2500
> 
> doacao = 0.1000
> 
> saldoAtual = saldoInicial - calça + salario - doacao 
> 
> arCondicionado = saldoAtual * 0.2500
> 
> saldoAtual = saldoAtual - arCondicionado 
> 
> divida = saldoAtual * 0.50
> 
> saldoAtual = saldoAtual - divida
> 
> console.log("O saldo atual é R$",saldoAtual.toFixed(2))
> ```

@Lorandi, vou comentar o seu também, ok ? :)

Da mesma forma, não há nenhum erro evidente. Mas vale alguns comentários:
- Não usamos caracteres especiais em nomes de variável. Logo `calça` não é um bom nome. Apesar de funcionar, podemos ter problemas em algumas situações. Portanto, evite usar caracteres especiais como "ç", acentos, "~" e coisas do tipo. 👍 
- No exercício 4, vc não chegou a guardar o valor da média em nenhuma variável. Não está errado, mas considerando que o `console.log` é apenas uma forma de exibir o valor na saída, em um programa um pouco maior seria interessante guardar isso antes de imprimir no console.

**Comment by GuiMichel** [comment]
> > Segue minhas soluções para comparação!
> > // Aula 05.06
> > // let saldo = 1000.00;
> > // saldo = saldo - 99.9;
> > // saldo = saldo + 2500;
> > // saldo = saldo - 0.1;
> > // saldo = saldo - (saldo*0.25);
> > // saldo = saldo - (saldo/2);
> > // console.log("Seu saldo é de "+saldo.toFixed(2)+" R$.");
> > // Aula 05.05
> > // let custoProdutos = 500;
> > // let receitaLiquida = 1000;
> > // let lucroBruto = receitaLiquida - custoProdutos;
> > // let margemBruta = (lucroBruto/receitaLiquida)*100;
> > // console.log("A margem bruta é de " +margemBruta+"%.");
> > // Aula 05.04
> > // let item1 = 2;
> > // let item2 = 2;
> > // let item3 = 2;
> > // let item4 = 2;
> > // let item5 = 2;
> > // let mediaAritmetica = 0;
> > // mediaAritmetica = (item1+item2+item3+item4+item5)/5;
> > // console.log(mediaAritmetica);
> > // Aula 05.03
> > // let boleto = 100.00;
> > // let juros = 0.1;
> > // let valorComJuros = 0;
> > // valorComJuros = boleto + (boleto*juros);
> > // console.log(valorComJuros);
> > // Aula 05.02
> > // let idade = 30;
> > // let maiorIdade = "true";
> > // maiorIdade = idade>=18;
> > // Aula 05.01
> > // let nomeDoFulano = "Fulano";
> > // let nomeDoCiclano = "Ciclano";
> > // mesmoNome = nomeDoFulano == nomeDoCiclano;
> 
> @GuiMichel Não existe nenhum erro na tua solução, porém vale um comentário:
> 
> Não há necessidade de declarar cada variável que tu for usar. Por exemplo, no exercício 05.02 vc não precisa iniciar a variável `maiorIdade`. Inclusive, a maneira que vc iniciou está incorreta, pois não usamos aspas em tipos booleanos. O correto seria `maiorIdade = true` (sem aspas). Não deu nenhum problema pois o JavaScript não tem tipagem forte, ou seja, uma variável pode assumir vários tipos no decorrer do código. No teu caso, ela iniciou sendo uma String com o valor "true" e depois virou um valor boolean do resultado da expressão `idade >= 18`.

Muito Obrigado pelos apontamentos @AlexandreSNeto ! Estava realmente com essas dúvidas!

**Comment by MoraesJorge** [comment]
Eaí pessoal, segue aí meu código para os exercícios da aula 05.
Comparando-o com os demais, boa parte está ficou bem semelhante.
Reparei que vocês usaram bastante "let" ao declarar as variáveis. Vou ter que dar uma pesquisada xD
Depois que aprendi a fazer funções, fiquei tão viciado que retornei aos exercícios e os reescrevi kkkk

```
// 1º exercício
mesmoNome = (nomeFulano == nomeBeltrano)

// 2º exercício
maiorDeIdade = (idade >= 18)

// 3º exercício
function calculaBoletoComJuros(valorBoleto, jurosAtraso){
    //valorBoleto (R$) e jurosAtraso(%)
    valorComJuros = (valorBoleto * (jurosAtraso/100+1))
    return console.log("O valor do boleto atualizado é: R$", valorComJuros.toFixed(2))
}

// 4º exercício
xBarra = (item1 + item2 + item3 + item4 + item5) / 5

// 5º exercício
function calculaMargemBruta(receitaLiquidaVendas, custoProdutosVendidos){
   lucroBruto = receitaLiquidaVendas - custoProdutosVendidos
   margemBruta = (lucroBruto / receitaLiquidaVendas) * 100
   return console.log("A margem bruta da empresa é:",margemBruta + "%")
}

// last but not least
saldoConta = 1000
saldoConta = saldoConta - 99.9
saldoConta = saldoConta + 2500
saldoConta = saldoConta - 0.1
saldoConta = saldoConta * 0.75
saldoConta = saldoConta * 0.5

console.log("Saldo ao final do dia: R$", saldoConta.toFixed(2))
```
Tenho duas dúvidas:
i) No exercício 3, o ideal é que a transformação de percentual para decimal ocorra fora da variável `valorComJuros` ou não
faz diferença para a performance da função?
ii) Devo utilizar sempre `return` na função, mesmo que seja uma impressão?

**Comment by vitorassi** [comment]
Bom dia @MoraesJorge, tudo bem?

Sobre suas Duvidas:

i) No exercício 3, o ideal é que a transformação de percentual para decimal ocorra fora da variável valorComJuros ou não
faz diferença para a performance da função?

R: Não existe uma forma padrão de fazer, vai depender muito do contexto da solução, no seu caso como está usando somente para um calculo talvez não faça sentido ter ele separado em outra variável, mas as vezes vai fazer sentido ter ele em uma variável para reaproveitar o valor e não ter que refazer o calculo (  "(jurosAtraso/100+1)" ) toda vez. Com relação a performance, no seu código o calculo sempre vai existir 1 vez, sendo ele armazenado em uma variável ou não, a diferença ficaria no custo de armazenar, se você colocar ela em uma variável vai ter que armazenar o valor para depois usar, se vc usar direto o custo de armazenar não vai existir, porém volto a ressaltar que no seu caso é utilizado 1 única vez, em casos que os cálculos são usados repetidamente sempre é mais viável armazenar em uma variável. 

ii) Devo utilizar sempre return na função, mesmo que seja uma impressão?
   Não precisa, o return indica que a function vai ter um retorno, muitas vezes porque o retorno sera usado por quem fez a chamada para a função, mas caso a function não tenha ideia, vc pode simplesmente imprimir o valor.


Espero ter ajudado, Até ....

**Comment by vitorassi** [comment]
> Eaí pessoal, segue aí meu código para os exercícios da aula 05.
> Comparando-o com os demais, boa parte está ficou bem semelhante.
> Reparei que vocês usaram bastante "let" ao declarar as variáveis. Vou ter que dar uma pesquisada xD
> Depois que aprendi a fazer funções, fiquei tão viciado que retornei aos exercícios e os reescrevi kkkk
> 
> ```
> // 1º exercício
> mesmoNome = (nomeFulano == nomeBeltrano)
> 
> // 2º exercício
> maiorDeIdade = (idade >= 18)
> 
> // 3º exercício
> function calculaBoletoComJuros(valorBoleto, jurosAtraso){
>     //valorBoleto (R$) e jurosAtraso(%)
>     valorComJuros = (valorBoleto * (jurosAtraso/100+1))
>     return console.log("O valor do boleto atualizado é: R$", valorComJuros.toFixed(2))
> }
> 
> // 4º exercício
> xBarra = (item1 + item2 + item3 + item4 + item5) / 5
> 
> // 5º exercício
> function calculaMargemBruta(receitaLiquidaVendas, custoProdutosVendidos){
>    lucroBruto = receitaLiquidaVendas - custoProdutosVendidos
>    margemBruta = (lucroBruto / receitaLiquidaVendas) * 100
>    return console.log("A margem bruta da empresa é:",margemBruta + "%")
> }
> 
> // last but not least
> saldoConta = 1000
> saldoConta = saldoConta - 99.9
> saldoConta = saldoConta + 2500
> saldoConta = saldoConta - 0.1
> saldoConta = saldoConta * 0.75
> saldoConta = saldoConta * 0.5
> 
> console.log("Saldo ao final do dia: R$", saldoConta.toFixed(2))
> ```
> 
> Tenho duas dúvidas:
> i) No exercício 3, o ideal é que a transformação de percentual para decimal ocorra fora da variável `valorComJuros` ou não
> faz diferença para a performance da função?
> ii) Devo utilizar sempre `return` na função, mesmo que seja uma impressão?

Bom dia @MoraesJorge, tudo bem?

Sobre suas Duvidas:

i) No exercício 3, o ideal é que a transformação de percentual para decimal ocorra fora da variável valorComJuros ou não
faz diferença para a performance da função?

R: Não existe uma forma padrão de fazer, vai depender muito do contexto da solução, no seu caso como está usando somente para um calculo talvez não faça sentido ter ele separado em outra variável, mas as vezes vai fazer sentido ter ele em uma variável para reaproveitar o valor e não ter que refazer o calculo ( "(jurosAtraso/100+1)" ) toda vez. Com relação a performance, no seu código o calculo sempre vai existir 1 vez, sendo ele armazenado em uma variável ou não, a diferença ficaria no custo de armazenar, se você colocar ela em uma variável vai ter que armazenar o valor para depois usar, se vc usar direto o custo de armazenar não vai existir, porém volto a ressaltar que no seu caso é utilizado 1 única vez, em casos que os cálculos são usados repetidamente sempre é mais viável armazenar em uma variável.

ii) Devo utilizar sempre return na função, mesmo que seja uma impressão?
Não precisa, o return indica que a function vai ter um retorno, muitas vezes porque o retorno sera usado por quem fez a chamada para a função, mas caso a function não tenha ideia, vc pode simplesmente imprimir o valor.

Espero ter ajudado, Até ....

**Comment by MoraesJorge** [comment]
@vitorassi, obrigado pela resposta.
Bah, ajudou bastante.

**Comment by wirthgabriele** [comment]
Exercício 6 pra mim ficou assim:

conta = 1000
calca = 99.90
salario = 2500
doacao = 0.10
saldo = conta - calca + salario - doacao
arCondicionado = saldo * 0.25
saldo = saldo - arCondicionado
saldo = saldo / 2

Resultado: 1275

**Comment by joprestes** [comment]
Segue minha resolução
//Saldo Final
saldoInicial= 1000;
calca = 99.9;
salario = 2500;
caridade = 0.1;
despesa = calca+caridade
saldoParcial = saldoInicial - despesa + salario;
arCondicionado = saldoParcial * 0.25 
dividaAntecipada = (saldoParcial - arCondicionado)  / 2;
saldoFinal = (saldoParcial - arCondicionado) - dividaAntecipada ;
console.log (saldoFinal);

**Comment by alexlimaxv** [comment]
Olá pessoal eu refiz o exercício 6 da aula 5 usando funções. Para todas as operações de compras eu usei a função de debito e para todas as receitas recebidas usei a operação de credito que acrescenta valor ao saldo corrente. A função percentualDoSaldo pode ser usada tanto para credito quanto para debito para isso passamos um percentual dentro da chamada da função. Como a função calcula baseado num valor percentual ela retorna um valor que pode ser usado nas funções de credito e debito.

```javascript
let saldo=1000;

function credito(valorCreditado){
saldo += valorCreditado;
}

function debito(valorDebitado){
  saldo -= valorDebitado;
} 

function percentualDoSaldo(porcentagem){
  return saldo * porcentagem;
}

function extrato(){
  console.log(saldo);
}

debito(99.90);
credito(2500);
debito(0.10);
debito(percentualDoSaldo(0.25));
debito(percentualDoSaldo(0.50));
extrato();
```

**Comment by Lucas-Bavaresco** [comment]
Estou recapitulando todas as Issues, muito legal a tua utilização das funções neste exercício @alexlimaxv !
