### ISSUE TITLE
POO

### ISSUE THREAD

**Issue by CarlosHeemann** [cwi-reset/edicao-02-qualificatoria#25]
Prezados, estou, acredito, numa mesma questão que deve ter afetado muitos: ter programado de forma linear e agora compreender Programação Orientada a Objetos(POO). Alguém tem um conceito bem básico que defina Programação Orientada para Objetos?

**Comment by CarlosHeemann** [comment]
Correção:" Leia ...que defina POO"

**Comment by SaimonFill** [comment]
neste link é explicado a diferença (com exemplos) entre POO e programação estruturada

https://www.devmedia.com.br/programacao-orientada-a-objetos-x-programacao-estruturada/31852

**Comment by CarlosHeemann** [comment]
Obrigado.

**Comment by Macenab** [comment]
Olá, tudo certo?! 

Falando a grosso modo, a POO é literalmente voltada a objetos, onde tu irá criar objetos com atributos, como exemplo uma bola, essa bola não será uma variável e sim um Objeto que terá atributos como exemplo: formato, cor, densidade, etc. Ou quem sabe pode criar um objeto CARRO que terá : marca, cor, quantidade de portas, Km rodados e velocidade máxima, etc.

Um dos benefícios disso é o reaproveitamento de código (toda vez que você usar o objeto CARRO, ele já trará todas essas informações) e mais facilidade na classificação dos objetos (caso queira fazer uma "lista" ou atribuir "regras" especiais a certos objetos).

Leitura complementar que traz mais conteúdos introdutórios à POO:
https://www.digitalhouse.com/br/blog/programacao-orientada-a-objetos-o-que-e

(Deixarei esse conceito bem básico para outras pessoas com essa mesma dúvida)

**Comment by CarlosHeemann** [comment]
Muito obrigado pelo retorno. Ajudou muito e focarei em entender a fundo a
POO.

Abração

Em seg., 4 de jan. de 2021 às 19:06, Bruno Macena <notifications@github.com>
escreveu:

**Comment by 89anderson** [comment]
> Olá, tudo certo?!
> 
> Falando a grosso modo, a POO é literalmente voltada a objetos, onde tu irá criar objetos com atributos, como exemplo uma bola, essa bola não será uma variável e sim um Objeto que terá atributos como exemplo: formato, cor, densidade, etc. Ou quem sabe pode criar um objeto CARRO que terá : marca, cor, quantidade de portas, Km rodados e velocidade máxima, etc.
> 
> Um dos benefícios disso é o reaproveitamento de código (toda vez que você usar o objeto CARRO, ele já trará todas essas informações) e mais facilidade na classificação dos objetos (caso queira fazer uma "lista" ou atribuir "regras" especiais a certos objetos).
> 
> Leitura complementar que traz mais conteúdos introdutórios à POO:
> https://www.digitalhouse.com/br/blog/programacao-orientada-a-objetos-o-que-e
> 
> (Deixarei esse conceito bem básico para outras pessoas com essa mesma dúvida)

Muito obrigado pela informação, esse link ta com a explicação bem legal e de fácil entendimento.
