### ISSUE TITLE
Dica de formatação de código no GitHub

### ISSUE THREAD

**Issue by AlexandreSNeto** [cwi-reset/edicao-02-qualificatoria#28]
Pessoal, quando forem incluir códigos aqui nas issues, tem um macete que deixa o código formatado, colorido e facilita muito a leitura do código.

Basta incluir o código dentro de um bloco que comece com 3 crases e a palavra "javascript" (colada nas crases) e ao final incluir mais 3 crases. Algo +/- assim:

![Exemplo](https://i.ibb.co/QDT4q4q/Screenshot-2.png)

Vai ficar dessa forma:

```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

**Comment by elciodalosto** [comment]
Eu me bati um monte ontem sem conseguir formatar o código e não consegui, agora testando com a dica deu certo :D

Mas dá para selecionar o texto que precisa ser formatado e clicar em "insert code", que ele insere as 3 crases automaticamente.
Eu estava primeiro clicando em "insert code" e depois colando o código, dai o github incluía apenas 1 crase, por isso não funcionava... a partir do momento em que comecei a colar o texto, selecionar apenas a parte com código e depois clicar em "insert code", passou a funcionar.

**Comment by AlexandreSNeto** [comment]
> Eu me bati um monte ontem sem conseguir formatar o código e não consegui, agora testando com a dica deu certo :D
> 
> Mas dá para selecionar o texto que precisa ser formatado e clicar em "insert code", que ele insere as 3 crases automaticamente.
> Eu estava primeiro clicando em "insert code" e depois colando o código, dai o github incluía apenas 1 crase, por isso não funcionava... a partir do momento em que comecei a colar o texto, selecionar apenas a parte com código e depois clicar em "insert code", passou a funcionar.

Perfeito @elciodalosto 
Porém a dica de incluir "javascript" facilita ainda mais, pois aparece o código colorido :D

**Comment by Lorandi** [comment]
@AlexandreSNeto Baita dica. Eu não entendia pq meu código não ficava colorido.

Ia perguntar na Issues #27 da questão 09 e magicamente ele coloriu. Agora fui ver que tu tinha editado.

Valeu

**Comment by lokyrech** [comment]
@AlexandreSNeto ótima call!!! Visualizar o código colorido facilita demais a interpretação...

**Comment by joprestes** [comment]
Agora tu não precisa mais editar as minhas postagens hauahsuhasu @AlexandreSNeto  >.>'  :P

**Comment by Lucas-Bavaresco** [comment]
Baita dica @AlexandreSNeto! Valeu pessoal... Eu também tava passando trabalho... hehe 

Sem dúvidas agrega muito por otimizar a visualização !
