### ISSUE TITLE
Live hoje

### ISSUE THREAD

**Issue by LFPires1993** [cwi-reset/edicao-02-qualificatoria#29]
Bom dia povo
Tenho apenas uma dúvida, a live será hoje mesmo (06/01)? E o link a ser utilizado será o mesmo da primeira live? Se estou me adiantando, perdão =}

**Comment by AlexandreSNeto** [comment]
@LFPires1993 sim, será hoje. O Link deve ser compartilhado hoje a tarde por e-mail para vocês :)

**Comment by LFPires1993** [comment]
Obrigado :)

**Comment by rakcruz** [comment]
Por falar nisso, ainda nao recebi o email sobre a live do dia 4. Alguém já recebeu?

**Comment by AlexandreSNeto** [comment]
Ainda não enviamos :)

**Comment by Lorandi** [comment]
Ótimo. Tb estava com essa dúvida.

**Comment by AlexandreSNeto** [comment]
Receberam o link ? :)

**Comment by Lorandi** [comment]
sim

**Comment by joprestes** [comment]
> Receberam o link ? :)

Sim... Obrigada!
