### ISSUE TITLE
Dúvida em Java. Jbutton buscar superclasse. 

### ISSUE THREAD

**Issue by wernerbastian** [cwi-reset/edicao-02-qualificatoria#31]
Oi, pessoal, tudo certo? Ainda não sei usar bem o GH, mas vamos lá.

Tô com dúvidas de como resolver uma questão aqui em **Java**, sou bem iniciante e tenho a dúvida surgiu na classe "Clientes", que tenho uma outra classe chamada "cadastrarClientes". **A dúvida é:** na classe "Clientes", o jbutton "cadastrar" precisa chmar a classe "cadastrarClientes", porém não estou fazendo certo. Alguém pode me dar um norte, por favor?  Ainda não sei os termos corretor a procurar.

Observação, ambas são classes pertencentes à mesma "mãe".

Segue o código em meu perfil:
[https://github.com/wernerbastian/testes](url)

**Comment by npoletto** [comment]
Olhei por cima, você está instanciando a classe dentro de um try, ficando "visível" apenas dentro dele.
Você precisa declará-la para que seja acessível a toda classe, apenas inicialize ela dentro do try.
Ex:

private Classequalquer qualquer;

(.....)

try {
qualquer = new ClasseQualquer();    //ao invés de ClasseQualquer qualquer = new ClasseQualquer();
} (...)

**Comment by npoletto** [comment]
Você não estaria instanciando cadastrarClientes (tente usar classes com letra maiúsculas) dentro de um try/catch? Ele ficará acessível apenas dentro do try.

**Comment by wernerbastian** [comment]
Oi, Poletto. Mas acho que a questão é como chamar ela (cadastrarClientes) como uma classe filha de uma outra (Clientes) que já é filha, e que venha no painel dela. Vou dar uma revisada geral no código, comentar alguns itens que não têm funcionalidade tbm. Já quanto ao try/catch, vou dar uma olhada tbm. Obrigado!

**Comment by npoletto** [comment]
Werner, uma dúvida um pouco fora do assunto, você vem de qual linguagem, antes de programar em Java?
A forma com que estás programando lembra bastante outras linguagens, o ideal seria começar a usar objetos e separar o máximo possível o que for view do que for regra de negócio. (se quiser pesquisar mvc, model view controller).
Cada arquivo de código está bem longo, acaba nos atrapalhando um pouco até para revisar.
Já trabalhei com Swing, mas faz muitos anos. Vi que você faz as consultas ao banco de dentro da view, um exercício bacana seria criar classes para apenas lidar com o banco de dados, e separar.
Outra coisa que lembrei, e que já tomei muito pau com o Swing, que é usar os JTables. O JTable em tese é bastante bacana quando você entende, pois ele parece muito complicado de cara. Você precisa usar um model para ele, e o ideal é não usar o model padrão, mas sim extender ele e adaptar para o teu caso.

**Comment by npoletto** [comment]
Outra coisa bastante interessante, utilize ArrayList ao invés deste lance aqui:
Object[][][][][][][][][][][] dados = {};

O ideal seria você criar um objeto Cliente, como um POJO (Plain Old Java Object - Velho e Simples Objeto Java).
O Pojo terá variáveis privadas acessíveis por métodos get/set. Como por exemplo: Nome, telefone, gênero, nascimento, etc.
O modelo da tua tabela será carregado com um ArrayList de objetos Clientes.
É apenas mais um dica...

**Comment by wernerbastian** [comment]
Oi, Poletto.

Estou aprendendo a programar agora, por isso ainda não sei me expressar da forma correta. E exato, você falou o correto, separar as views da regra mesmo.

Como nunca programei, eu estou tentando trabalhar em cima do código que aprendo em aula, adaptando-o para o que preciso, por isso ainda não entendo bem. 

Você tem alguma dica de curso para aprender melhor? Estou vendo uns da Digital One, mas não estou entendendo muito bem.

Ah! Se você olhar agora, eu atualizei o código, está funcional, porém alterei a opção para cadastrar, ela está sendo possível ser chamada apenas pela classe principal do pacote. Obrigado pelas dicas.
