### ISSUE TITLE
sobre mais exercícios 

### ISSUE THREAD

**Issue by nobregadanilo** [cwi-reset/edicao-02-qualificatoria#32]
Oi, queria saber novos exercícios de cada etapa para continuar treinando depois de acabar os das aulas

**Comment by Lorandi** [comment]
Fiz a sugestão no chat da live, mas colo aqui pois acho a ferramenta genial:
https://www.urionlinejudge.com.br/judge/pt

**Comment by MoraesJorge** [comment]
À medida que nós formos vencendo os conteúdos, podemos criar pequenos desafios (claro, baseado no nível dos exercícios das aulas) para nós resolvermos aqui no Github.

Por exemplo:  criar um algoritmo que converte temperatura em graus Celsius(ºC) para Fahrenheit(ºF).

O que acham?

**Comment by AlexandreSNeto** [comment]
> À medida que nós formos vencendo os conteúdos, podemos criar pequenos desafios (claro, baseado no nível dos exercícios das aulas) para nós resolvermos aqui no Github.
> 
> Por exemplo: criar um algoritmo que converte temperatura em graus Celsius(ºC) para Fahrenheit(ºF).
> 
> O que acham?

Baita ideia!

**Comment by nobregadanilo** [comment]
> Fiz a sugestão no chat da live, mas colo aqui pois acho a ferramenta genial:
> https://www.urionlinejudge.com.br/judge/pt

ja to dando uma olhada aqui, parece interessante

**Comment by SaimonFill** [comment]
esse site da 

> Fiz a sugestão no chat da live, mas colo aqui pois acho a ferramenta genial:
> https://www.urionlinejudge.com.br/judge/pt

é muito bom esse site para praticar, tem vários níveis de exercícios.

**Comment by sergioribeiros** [comment]
Boa noite pessoal. sobre os exercícios, tem esse curso de 4 horas sobre JavaScript com exercícios bem desafiadores durante ele. (https://www.youtube.com/watch?v=i6Oi-YtXnAU&t=11616s) Fica minha dica a todos 👍🏾

**Comment by MTheobald86** [comment]
Genial essa issue! Gratidão pela ideia e pelas dicas!

**Comment by lokyrech** [comment]
Eai galerinha,

Aproveitando que vi que estão buscando desafios extras, gostaria de indicar o [Codewars](https://www.codewars.com/), que é uma plataforma muito legal com diversos desafios e classificação de níveis tanto para os desafios quanto para os usuários.

Estou utilizando-me desta plataforma para treinar e melhorar minhas skills tanto em Java, quanto JavaScript e estou adorando a forma com que a plataforma lida com os níveis de programação.

Quem sabe poderiamos fazer umas "competiçõezinhas" por lá! Se alguém topar basta me chamar!

OBS: Um ponto muito legal desta plataforma é que após a resolução do exercício proposto ele apresenta diversas formas de soluciona-lo, é um vislumbre as vezes perceber que uma solução que você desenvolveu em umas 20 linhas de código pode ser solucionada em 2 linhas HEHEHEH!

Abraços,
Lucas Rech.

**Comment by pedropietro** [comment]
Lista de algorítimo básico

https://www.dca.ufrn.br/~affonso/DCA800/pdf/exercicios_algoritmos.pdf

https://www.dca.ufrn.br/~affonso/DCA800/pdf/exercicios_algoritmos2.pdf

https://www.dca.ufrn.br/~affonso/DCA800/pdf/Exe_1.pdf

https://www.dca.ufrn.br/~affonso/DCA800/pdf/Exe_2.pdf

https://www.dca.ufrn.br/~affonso/DCA800/pdf/Exe_3.pdf

https://www.dca.ufrn.br/~affonso/DCA800/pdf/Exe_4.pdf



Lista de execícios de orientação à objeto em java:

http://nbcgib.uesc.br/nbcgib/files/LP-III/ListaExercicios-01.pdf
http://nbcgib.uesc.br/nbcgib/files/LP-III/ListaExercicios-02.pdf
http://nbcgib.uesc.br/nbcgib/files/LP-III/ListaExercicios-03.pdf
http://nbcgib.uesc.br/nbcgib/files/LP-III/ListaExercicios-04.pdf

**Comment by lukas8219** [comment]
Recomendo usar o CodeWars. Onde tu pode ir ter graduando enquanto tu completa os desafios. São 8 níveis, e alguns exercícios que aparecem ali, podem aparecer até mesmo em entrevista de emprego Junior/Pleno, dependendo do nível delas.

https://www.codewars.com/

**Comment by nobregadanilo** [comment]
nossa, vou dar uma olhada nesse codewars essa semana, por sinal gostei da ideia do amigo la em cima de fazer grupos

**Comment by Lorandi** [comment]
> Recomendo usar o CodeWars. Onde tu pode ir ter graduando enquanto tu completa os desafios. São 8 níveis, e alguns exercícios que aparecem ali, podem aparecer até mesmo em entrevista de emprego Junior/Pleno, dependendo do nível delas.
> 
> https://www.codewars.com/

Demais esse codewars
Quem fizer sing up adiciona lá para trocarmos infos
https://www.codewars.com/users/Lorandi

**Comment by nobregadanilo** [comment]
eu acabei tendo dificuldades nele por conta do idioma, dai to preferindo o URI ( https://www.urionlinejudge.com.br/judge/pt )

**Comment by lukas8219** [comment]
Opa, boa ideia @Lorandi 

https://www.codewars.com/users/lukas8219

Quem quiser me adicionar lá tb.
