### ISSUE TITLE
Aula 5 - Operadores

### ISSUE THREAD

**Issue by juaumcarlus** [cwi-reset/edicao-02-qualificatoria#34]
Galera e assim que comecei a resolver as questão 1 a 3 da Aula 5, mais depois a forma que foi criado e estou bem longe de entender,
![image](https://user-images.githubusercontent.com/76566100/103836412-c3194980-5067-11eb-9a81-cedb043b44d0.png)

**Comment by 89anderson** [comment]
> Galera e assim que comecei a resolver as questão 1 a 3 da Aula 5, mais depois a forma que foi criado e estou bem longe de entender,
> ![image](https://user-images.githubusercontent.com/76566100/103836412-c3194980-5067-11eb-9a81-cedb043b44d0.png)

O que exatamente tu não conseguiu entender @juaumcarlus ?

O "a", "b" e "c" são variáveis, basicamente são "potinhos" onde armazenamos informaçõs.

Na pergunta 1, por exemplo, temos a seguinte situação:

a = ("joao"): a palavra "joao" está sendo armazenada em a.
b = ("jorge"): a palavra "jorge" está sendo armazenada em b.

c = (a == b): aqui,  "c" está recebendo uma comparação entre o potinho "a" e o potinho "b". os " == " é a sintaxe para representar a pergunta a "é igual a" b ( a == b)?

por fim, temos o comando que vai escrever no terminal o que guardamos dentro de "c":

console.log() é o comando que significa "escreva na tela".

E dentro dos parênteses do console.log, a gente informa o que quer que seja escrito.

No caso console.log(c) vai emitir na tela a informação armazenada no "potinho" c, que recebeu a informação da pergunta "a é igual a b?" (a == b).

Se A for igual a B, então C recebe a informação VERDADE (true), se A for diferente de B, então C recebe a informação FALSO(false).

Tentei ser o mais simplista possível, espero que eu tenha conseguido te explicar...

Qualquer coisa pode perguntar novamente.

Abraços e bons estudos.

**Comment by RafaelStefaniBaptista** [comment]
Boa noite @juaumcarlus

Vamos lá.

Primeiramente o objetivo da aula 5 é exercitar o uso dos operadores aritméticos e lógicos.
Sendo alguns deles:

Igualdade (==)
Maior ou igual (>=)
Multiplicação (*)
Adição (+)
Divisão (/)
Subtração)

Tuas questões 1 e 2 estão corretas.

Na questão 3 temos somente que fazer um acréscimo de 10% ao valor, ou seja, supondo que o valor seja 200.
Poderíamos solucionar da seguinte maneira:

```
valorBoleto = 200
valorDoJuros = valorBoleto * (10 / 100)
valorComJuros = valorBoleto + valorDoJuros
```

Que na prática o resultado é o mesmo da resolução dos exercicios.

Concorda comigo que se eu fizer (10 dividido por 100) é 10% e fazendo 10% vezes o valorBoleto temos 10% do valorBoleto?

E então somamos 10% do valorBoleto ao valorBoleto.

Tu tens alguma dúvida quanto a questão 3?

Na questão 4 tudo que precisa ser feito é uma média dos valores.

O cálculo de média é bem simples é a soma dos valores dividido pela quantidade:

```
item1 = 1
item2 = 2
item3 = 3
item4 = 4
item5 = 5

quantidadeDeItens = 5

media = (item1 + item2 + item3 + item4 + item5) / quantidadeDeItens

```

Tendo em vista os valores 1 2 3 4 5 como exemplo o resultado da média é 3.

Na questão 5 temos varias informações eu recomento realizar as operações passo a passa por etapas, por exemplo:

No enuncia temos que "O lucro bruto de uma empresa é representado pela receita líquida de vendas menos o custo dos produtos vendidos", logo traduzindo isto para linguagem de programação temos:

```
lucroBruto = receitaLiquidaVendas - custoProdutosVendidos
```

Depois "A margem bruta de uma empresa é calculada pela divisão do lucro bruto pela receita líquida de vendas."

```
margemBruta = lucroBruto / receitaLiquidaVendas
```

Então "Faça a representação da fórmula da margem bruta, multiplicando o resultado final por 100 para obter o valor percentual;"

```
lucroBruto = receitaLiquidaVendas - custoProdutosVendidos
margemBruta = lucroBruto / receitaLiquidaVendas
percuentualDaMargemBruta = margemBruta * 100
```

Acredito que assim seja mais fácil de visualizar o problema. (uma abordagem bastante utilizada inclusive)

E por fim na questão 6 é uma junção de tudo:

Atribuir R$ 1000,00 ao saldo.
Subtrair R$ 99,90 do saldo.
Somar R$ 2500,00 ao saldo.
Subtrair R$ 0,10 do saldo.
Subtrair 25% do seu saldo atual.
Subtrair metade do saldo.

```
saldo = 1000
saldo = saldo - 99.90
saldo = saldo + 2500
saldo = saldo - 0.1
saldo = saldo * 0.75
saldo = saldo / 2
console.log(saldo)
```

Resultado 1275.

**Comment by AntonioHReis** [comment]
Olá juaumcarlus

1 - Crie uma variável mesmoNome que verifica se nomeDoFulano é igual a nomeDoBeltrano;

Aqui o que você precisa entender é o que o enunciado está pedindo, é a parte mais importante, junto com o estudo das aulas anteriores, que devem ser bem entendidas para seguir em frente, caso isto não esteja ocorrendo você deve voltar as aulas anteriores e dar uma olhada novamente, com calma e tranquilidade.

Vamos ver se pegamos apenas o primeiro exercício para começar:

Pelo enunciando temos que criar uma variável que é lógica (Verdadeiro ou falso)

mesmoNome = true   

por exemplo

e as outras duas são para conter nomes

nomeDoFulano = "João"
nomeDoBeltrano = "Pedro"

agora vamos ver se são nomes iguais, e para isto temos que compara os nomes

nomeDoFulano == nomeDoBeltrano

mas, se deixarmos desta forma o resultado não fica em lugar algum, então atribuímos o resultado a váriavel mesmoNome

mesmoNome = nomeDoFulano == nomeDoBeltrano

Rodando este programa deve dar False, porque são diferentes
Se mudar o nome para ser iguais e rodar novamente deverá dar true

Espero ter ajudado.

Um abraço!
Antonio H Reis

**Comment by Lorandi** [comment]
> Galera e assim que comecei a resolver as questão 1 a 3 da Aula 5, mais depois a forma que foi criado e estou bem longe de entender,
> ![image](https://user-images.githubusercontent.com/76566100/103836412-c3194980-5067-11eb-9a81-cedb043b44d0.png)

Olá @juaumcarlus 

Além da excelente explicação do @89anderson , convém ressaltar que quando aparece apenas um o sinal **=** deve ser entendido como **recebe** e não como **igual**. 
   ```javascript
 a = "João"
   //Estas dizendo para o computador que "a" significa "João".

```
 No entanto quando aparece duplo **==** está fazendo uma comparação, verificando se o que vem antes e depois é igual, esperando que disso venha um resultado verdadeiro(true) ou falso(false). 

Ou seja, a variável **a** _recebe_ o nome **João**, a variável **b** _recebe_ o nome **Jorge**

Já a variável **c** recebe a comparação estre as duas variáveis **a** e **b**. Caso sejam exatamente iguais, retorna **true**. Caso contrário retorna **false**. Essa comparação serve para palavras, chamadas de **strings**, ou para números.

Posta mais sobre a tua dúvida para sabermos se estamos respondendo o que não entendeu.

**Comment by juaumcarlus** [comment]
Acho que então eu cheguei na resposta mais montando de outra forma.
Tipo a questão 1 eu utilizei as letras A,B, e C no lugar
mesmoNome ( C)
nomeFulano (A)
nomeBeltrano ( B) 

Pois da forma que montei e rodando deu False e se alterar para mesmo da True.

**Comment by AlexsonT** [comment]
> Acho que então eu cheguei na resposta mais montando de outra forma.
> Tipo a questão 1 eu utilizei as letras A,B, e C no lugar
> mesmoNome ( C)
> nomeFulano (A)
> nomeBeltrano ( B)
> 
> Pois da forma que montei e rodando deu False e se alterar para mesmo da True.

Oi @juaumcarlus,  

Uma dica: quando fores postar o teu código, copia e cole ele aqui ou use o ícone"<>" que aparece em cima da caixa de texto aqui do Github. Assim podemos copiar teu código e executar pra tentar entender melhor teu problema. 

Outra coisa que percebi no teu código é que escreveu "Exercício Aula 5" no início. Não sei se chega a te atrapalhar nesse caso, mas sempre que for colocar alguma informação que não seja código utilize comentário, caso contrário, pode estar executando a informação junto ao código e até ocasionando um erro. Para comentar utilize // no início ou com o comando Ctrl+;

Li o que os colegas postaram aí em cima e acredito que está bem explicado. 

Obs: posta te código novamente, como ele está gora, e nos diga quais são as dúvidas em cada etapa, com certeza vamos te ajudar a entender.

**Comment by AlexandreSNeto** [comment]
Uma dica importante é nomear as variáveis com sentido. Usar "a", "b" e "c" em um exercício de cálculos matemáticos, até faz sentido, pois fazemos isso no dia a dia também.

Mas no caso de nomes, "a" não me diz muita coisa. Olhando somente o código que você postou, ficou difícil de entender qual era o exercício.

Então fica a dica pra geral: usem nomes de variáveis que façam sentido. Para o computador, não faz diferença se a variável é "a" ou "nomeDaVariavelEnormeQueONetoCriou". Escrevam código para outros humanos lerem. 

🚀

**Comment by proaldo** [comment]
![Captura de Tela 2021-01-12 às 19 14 16](https://user-images.githubusercontent.com/76567702/104403078-7d142800-5536-11eb-8088-b0f651c03fe2.png)

Galera, boa noite. Gostaria da opinião de vocês...
Eu elaborei essa reposta diferente da forma proposta pela equipe CWI (embora tenha chegado no mesmo resultado), dessa forma acham que fica pouco intuitivo?
Obrigado desde já! =)

**Comment by proaldo** [comment]
![Captura de Tela 2021-01-13 às 00 35 46](https://user-images.githubusercontent.com/76567702/104403451-4be82780-5537-11eb-81d6-7cef393bafec.png)
Boa noite, pessoas. =D
Gostaria de ma sugestão. Nesse exercício 06 da aula 05 eu montei o algoritmo da questão de uma forma diferente como proposto na resolução pela equipe CWI (embora tenha chegado no mesmo resultado), mas essa forma parece pouco intuitiva?
Obrigado desde já! =)

**Comment by Lorandi** [comment]
> ![Captura de Tela 2021-01-13 às 01 45 06](https://user-images.githubusercontent.com/76567702/104407703-fd3f8b00-5540-11eb-9638-0a87bee68b89.png)
> 
> Boa noite pessoal. =D
> Gostaria de uma sugestão. Nesse exercício 06 da aula 05 eu montei o algoritmo da questão de uma forma diferente de como foi proposto na resolução pela equipe CWI (embora tenha chegado no mesmo resultado), mas essa forma parece pouco intuitiva?
> Obrigado desde já! =)

Olá @proaldo 
Eu não vejo como prevalente o uso de valores negativos para os preços dos produtos mas deu para entender o que teu código se propõe. Só tem que lembrar que ao invés de subtrair os valores do saldo, tens que adicionar, como fizeste.
