### ISSUE TITLE
O que os Cursos NÃO te Ensinam sobre Mercados

### ISSUE THREAD

**Issue by Lorandi** [cwi-reset/edicao-02-qualificatoria#35]
Mais uma pedrada do Fabio Akita.

Não veja esse vídeo caso espere manter a ilusão de caminhos fáceis na programação.

https://www.youtube.com/watch?v=L0hTOY5n9G8

**Comment by 89anderson** [comment]
> Mais uma pedrada do Fabio Akita.
> 
> Não veja esse vídeo caso espere manter a ilusão de caminhos fáceis na programação.
> 
> https://www.youtube.com/watch?v=L0hTOY5n9G8

Boa @Lorandi !!

É bem o que a galera expôs ontem na live. Não tem moleza :P

**Comment by GuiMichel** [comment]
> Mais uma pedrada do Fabio Akita.
> 
> Não veja esse vídeo caso espere manter a ilusão de caminhos fáceis na programação.
> 
> https://www.youtube.com/watch?v=L0hTOY5n9G8

Os videos do Akita são só soco no estômago...
Pra ficar esperto e não num conto de fadas.

**Comment by Davidjordao** [comment]
> Mais uma pedrada do Fabio Akita.
> 
> Não veja esse vídeo caso espere manter a ilusão de caminhos fáceis na programação.
> 
> https://www.youtube.com/watch?v=L0hTOY5n9G8

Muito bom !!!

**Comment by AntonioHReis** [comment]
Pura verdade!

**Comment by lokyrech** [comment]
> Mais uma pedrada do Fabio Akita.
> 
> Não veja esse vídeo caso espere manter a ilusão de caminhos fáceis na programação.
> 
> https://www.youtube.com/watch?v=L0hTOY5n9G8

Bá vendo os primeiros 5 minutos do vídeo, me deparei com minha própria realidade. Formei-me Engenheiro Mecânico no ano passado, quando iniciei a faculdade estavamos no que o Akita chamou de "ciclo de abundância" na área (ou seja, na época eram cerca de 12 mil vagas sem profissionais para preenche-las), porém quando finalizei o curso deparei-me com um tremendo "ciclo de depressão".

Devido a alta demanda de profissionais do ramo de engenharia, muitas pessoas resolveram seguir para essa área o que acabou ocasionando em um grande excesso de profissionais, logo temos muitos engenheiros e arrumar um emprego na área tornou-se uma tarefa quase que impossível!!!

Espero conseguir seguir nesta oportunidade da CWI para iniciar minha carreira nesta nova área e não passar novamente por um ciclo de depressão!!! HEHEHE

#soconoestomago #medo

**Comment by SaimonFill** [comment]
> Mais uma pedrada do Fabio Akita.
> 
> Não veja esse vídeo caso espere manter a ilusão de caminhos fáceis na programação.
> 
> https://www.youtube.com/watch?v=L0hTOY5n9G8

sensacional! Um choque de realidade e para abrir a mente!
