### ISSUE TITLE
Ajuda para desafio extra

### ISSUE THREAD

**Issue by GuiMichel** [cwi-reset/edicao-02-qualificatoria#37]
Pessoal estava eu resolvendo alguns problemas no site [https://www.hackerrank.com](url)
Até que me deparei com esse problema. [https://www.hackerrank.com/challenges/diagonal-difference/problem](url)

A questão é que ele da um erro no site porém no Repl.it eu faço e da certo...
se alguem puder ajudar fico muuuito feliz pois estou a hrs testando coisas diferentes.

segue o erro e o cód.
```javascript
function diagonalDifference(arr) {
    var tamanho = arr[0][0];
    var i=0;
    var j=0;
    var d1=0;
    var d2=0;
    
    for(i=1;i<(tamanho+1);i++){
        for(j=0 ; j<3 ; j++){            
            if(i-j==1){           
              d1 += arr[i][j];
            }
            if(i+j==tamanho){
              d2 += arr[i][j];
            } 
            }
        } 
    resultado = d1-d2;
    return Math.abs(resultado);
}

ar = [
      [3,,],
      [11,2,4],
      [4,5,6],
      [10,8,-12]
];

diagonalDifference(ar);
```
![image](https://user-images.githubusercontent.com/76564941/103922475-8fcfcc80-50f2-11eb-8ce5-8d565f960255.png)

**Comment by GuiMichel** [comment]
> Pessoal estava eu resolvendo alguns problemas no site [https://www.hackerrank.com](url)
> Até que me deparei com esse problema. [https://www.hackerrank.com/challenges/diagonal-difference/problem](url)
> 
> A questão é que ele da um erro no site porém no Repl.it eu faço e da certo...
> se alguem puder ajudar fico muuuito feliz pois estou a hrs testando coisas diferentes.
> 
> segue o erro e o cód.
> 
> ```js
> function diagonalDifference(arr) {
>     var tamanho = arr[0][0];
>     var i=0;
>     var j=0;
>     var d1=0;
>     var d2=0;
>     
>     for(i=1;i<(tamanho+1);i++){
>         for(j=0 ; j<3 ; j++){            
>             if(i-j==1){           
>               d1 += arr[i][j];
>             }
>             if(i+j==tamanho){
>               d2 += arr[i][j];
>             } 
>             }
>         } 
>     resultado = d1-d2;
>     return Math.abs(resultado);
> }
> 
> ar = [
>       [3,,],
>       [11,2,4],
>       [4,5,6],
>       [10,8,-12]
> ];
> 
> diagonalDifference(ar);
> ```
> 
> ![image](https://user-images.githubusercontent.com/76564941/103922475-8fcfcc80-50f2-11eb-8ce5-8d565f960255.png)

![image](https://user-images.githubusercontent.com/76564941/103922651-cdccf080-50f2-11eb-832f-a8c300c3c36f.png)

![image](https://user-images.githubusercontent.com/76564941/103922785-04a30680-50f3-11eb-8fda-d78eb8089589.png)

![image](https://user-images.githubusercontent.com/76564941/103922885-2e5c2d80-50f3-11eb-97a7-97f1a3a252bc.png)



imagens do desafio.

**Comment by GuiMichel** [comment]
Galera intendi o que estava errado...
eu havia interpretado errado qual seria o input que o site mandaria para testar...
eu havia intendido assim:

![image](https://user-images.githubusercontent.com/76564941/103932904-49ce3500-5101-11eb-87dd-1c91fce70bd4.png)

que esta imagem queria dizer esse cód:
```javascript
ar = [
      [3,,],
      [11,2,4],
      [4,5,6],
      [10,8,-12]
];
```

e na verdade era assim:

```javascript
ar = [
      [11,2,4],
      [4,5,6],
      [10,8,-12]
];
```
então a solução ficou assim:

```javascript
function diagonalDifference(arr) {
    var tamanho = arr[0].length;
    var i=0;
    var j=0;
    var d1=0;
    var d2=0;
    console.log(tamanho);
    for(i=0;i<tamanho;i++){
        for(j=0 ; j<tamanho ; j++){            
            if(i==j){           
              d1 += arr[i][j];
            }
            if(i+j==2){
              d2 += arr[i][j];
            } 
            }
        } 
    resultado = d1-d2;
    return Math.abs(resultado);
}
```

**Comment by Lorandi** [comment]
Eu ia te comentar isso, que  aquele 3 não fazia parte da matriz. Como ainda não tinha conseguido fazer funcionar, estava aqui quebrando cabeça.

Que bom que solucionou

**Comment by Lorandi** [comment]
Mas o resultado que esperado era 15 e está dando 3.

**Comment by GuiMichel** [comment]
> Mas o resultado que esperado era 15 e está dando 3.

Dae @Lorandi !
Muito obrigado por dedicar seu tempo a ajudar!
eu acho q o 3 que tu esta visualizando é do console.log que eu botei para testar o tamanho da array.
testei aqui e da 15 o resultado.
segue a imagem:
![image](https://user-images.githubusercontent.com/76564941/103937357-69685c00-5107-11eb-9519-b45363dec535.png)

mais uma vez obrigado!

**Comment by Lorandi** [comment]
> > Mas o resultado que esperado era 15 e está dando 3.
> 
> Dae @Lorandi !
> Muito obrigado por dedicar seu tempo a ajudar!
> eu acho q o 3 que tu esta visualizando é do console.log que eu botei para testar o tamanho da array.
> testei aqui e da 15 o resultado.
> segue a imagem:
> ![image](https://user-images.githubusercontent.com/76564941/103937357-69685c00-5107-11eb-9519-b45363dec535.png)
> 
> mais uma vez obrigado!

Sim, era isso mesmo. Tinha até apagado essa minha postagem mas talvez só desapareça para mim. Vi que tava dando 15 quando incluí o console.log (return Math.abs(resultado))

Essa questão não é moleza.

 Bons estudos

**Comment by lokyrech** [comment]
Eai galerinha,

Aproveitando que vi que estão buscando desafios extras, gostaria de indicar o [Codewars](https://www.codewars.com/),  que é uma plataforma muito legal com diversos desafios e classificação de níveis tanto para os desafios quanto para os usuários.

Estou utilizando-me desta plataforma para treinar e melhorar minhas skills tanto em Java, quanto JavaScript e estou adorando a forma com que a plataforma lida com os níveis de programação.

Quem sabe poderiamos fazer umas "competiçõezinhas" por lá! Se alguém topar basta me chamar!

Abraços,
Lucas Rech.

**Comment by EduardaBatistella** [comment]
Boa noite pessoal,

Outro site interessante com muitos desafios é o urionlinejudge.com.br. Bem interessante para treinar. 

Abraços,

Eduarda
