### ISSUE TITLE
Material de Estudo - Sistema Operacional e Conceitos - Algoritmos e Lógica de Programação 

### ISSUE THREAD

**Issue by alexlimaxv** [cwi-reset/edicao-02-qualificatoria#41]
Olá pessoal boa tarde!
Eu transcrevi o material da aula de Sistemas operacionais para estudar. Penso que pode ajudar em nossos estudos.

Sistema operacional

Conceito: Conjunto de softwares que permite a operação de um computador ou um equipamento similar.

Permite acessar e controlar o hardware da maquina, alocar recursos e interagir com aplicações diversas. Gerencia processos de comunicação via rede, permitindo a troca de dados entre programas e dispositivos, além de efetuar tratamento de erros.

Kernel: Componente central de um sistema operacional. É a primeira parte do SO a carregada e permanece na memória principal. Suas principais funções são:

Gerenciamento de memória 
Gerenciamento de processos 
Gerenciamento de armazenamento 
Gerenciamento de dispositivos 

Existem vários tipos de kernels como:

Monolitico 
Microkernel
Híbrido 
Exokernel 
Nano Kernel

Processos e Threads 

Processo é um programa em execução. Processos são gerenciados pelo SO, o qual também controla o agendamento de processos (scheduling). Uma threading é um fluxo de execução separado dentro de um processo, também chamada de lightweight  process(processo leve) permite melhorar a performance de uma aplicação por meio de paralelismo. 

Tipos de SO

Sistema operacional em lote - Mainframe
De tempo compartilhado
Distribuido
De rede - linux e win server
De tempo real - airbag - airplane
Multitarefa e Multiprogramação 

Multitarefa significa que diversas tarefas podem ser executadas pela CPU simultaneamente, pela comutação entre elas, de forma muito rápida. 

Multiprogramação significa que a CPU pode ser compartilhada por dois ou mais programas na memória ao mesmo tempo, aumentando sua utilização. 

Familia de sistemas operacionais 

Baseados em Unix 				Windows 

BSD				
Solaris 			
Linux 			
OSX				
Android 
IOS
Windows 3.11
Windows 98
Windows XP
Windows Server 
Windows 7
Windows 10

Além das duas grandes famílias citadas anteriormente existem e existiram outros sistemas operacionais empregados em sistemas especializados do tipo mainframes, RTOS, ou ainda em soluções IoT tais como:

OS/2			
Opem VMS	
BeOs			
Free RTOS		
LynxOS
Symbian OS
VX Works
Huawei lite OS

Tipos de interfaces: CLI, GUI e Terminals 

CLI: Command Line interface - Interface de linha de comando. É Controlado por meio de comandos emitidos em um prompt.

GUI: Graphical User Interface - Interface Gráfica. O sistema é controlado por meio de elementos gráficos com um dispositivo apontador, como mouse ou via touch. 

Terminal: Software que emula um terminal de hardware, geralmente interface de linha de comandos que pode ser executada dentro de uma interface gráfica. 

Sistema de arquivos (File System)

Forma de organização de dados em uma mídia de armazenamento, como um HD. Os dados são organizados geralmente em pastas (diretórios) e indexados para que seja possível localiza-los quando necessário. 

Há vários tipos de sistemas de arquivos de acordo com o SO ou mídia:

Windows: FATS, NTFS, ExFAT
Linux: EXT3, EXT4, BTRFS
Apple: HFS+
Mídias ópticas: ISO 9660, UDF
Unixes: UFS, ZFS, XFS

O sistema é criado pelo processo de formatação de uma partição.

Segurança: Firewall, Backup, Antivirus.

Não fazem exatamente parte dos SO’s, mas são parte essencial do sistema computacional em si, pois ajudam a proteger os SO’s, programas e arquivos dos usuários.

Firewall: Bloqueia pacotes suspeitos ou indesejados.
Antivirus: Protege contra ataques de malwares.
Backup: Ferramenta para cópia de segurança de dados.

A maioria dos SO’s possuem ferramentas básicas integradas que realizam essas funções. 

O que são aplicativos, utilitários e serviços

Aplicativo é um programa com função específica, muitas vezes instalado pelo próprio usuário, como softwares de planilhas ou jogos.

Utilitário é um programa aplicativo que permite realizar tarefas administrativas no sistema, como desfragmentação de disco, configuração de contas, otimização de desempenho.

Serviços são processos internos do sistema que gerenciam determinadas funcionalidades ou outras aplicações. 
Exemplos incluem: Cliente DHCP, Horário do sistema, log de eventos, spooler de impressão, geolocalização, MySQL Server e etc.

Ferramentas de gerenciamento

Todo sistema operacional possui diversas ferramentas de gerenciamento (utilitários), é importante conhecê-las e saber utilizá-las.

Exemplos no Windows:
compmgmt (gerenciamento do computador)
services (gerenciamento de serviços)
regedit (Editor de registros)
task manager (Gerenciador de tarefas)
gerenciadores de pacotes (chocolatey, oneGet etc.)

Virtualização de Máquinas Virtuais

Tecnologia que permite múltiplos ambientes a partir de um sistema físico único. Um software chamado de Hypervisor permite criar máquinas virtuais, dividindo o hardware do computador em ambientes separados. 
A maquina física é chamada de Host (hospedeiro), e as maquinas virtuais são chamadas de Guests (convidados).

Existem várias formas de virtualização, como sistemas operacionais diferentes, de discos, Rede, de aplicações, de Desktops, etc.

Algoritmos

Todo fluxo computacional criado para resolver um problema pode ser chamado de algoritmo. Um algoritmo é, literalmente, uma sequencia lógica de passos com um início, meio e fim, que foi concebida para resolver algum problema específico.
Pode ser entendido como uma sequência de raciocínios, instruções ou operações para alcançar um objetivo, sendo necessário que os passos sejam finitos e operados sistematicamente. 

Lógica de programação 

A lógica está juntamente no desenvolvimento dessa capacidade analítica aprofundada para resolução de problemas, os quebrando em algoritmos.

**Comment by thaisbg** [comment]
Muito obrigada por compartilhar conosco, realmente fica muito mais fácil revisar lendo :D

**Comment by GuiMichel** [comment]
Muito bom esse resumão!! vlw @alexlimaxv !!!

**Comment by Lorandi** [comment]
Muito bom @alexlimaxv 

Talvez tenha ocorrido um erro na hora de colar o conteúdo aqui no Github pois ficou **Famílias de sistemas operacionais**  **Baseados em Unix Windows** dando a impressão que é uma coisa só.

São duas famílias separadas.

**Baseados em Unix:** 
BSD
Solaris
Linux
OSX
Android
IOS

**Baseados em Windows:** 
Windows 3.11
Windows 98
Windows XP
Windows Server
Windows 7
Windows 10
DOS*(precursor do sistema windows)

**Comment by Lorandi** [comment]
Se quiser pesquisar direto no minuto do vídeo:

1.	00:00  O que é um sistema operacional; 
2.	01: 15 Kernel(cerne): Central de um sistema operacional. Primeiro a ser carregado e fica na memória;
3.	02:50 Processos(programa em execução) e Threads(fluxo de execução);
4.	04:30 Tipos de sistemas operacionais;
5.	05:30 Multitarefa e multiprogramação;
6.	07:10 Famílias de sistemas operacionais;
7.	09:45 Tipos de interfaces: CLI(command-line interface), GUI (Graphical User Interface) e terminais (software que emula um terminal);
8.	11:20 Sistemas de arquivos (File System);
9.	13:35 Segurança: Firewall, Backup, Antivírus;
10.	15:15 O que são aplicativos,utilitários e serviços;
11.	17:40 Ferramentas de gerenciamento;
     a.	Compmgmt(Gerenciamento do computador);
     b.	Services (Gereciamento de Serviços);
      c.	Regedit(Editor do Registro);
     d.	Task Manager (Gerenciador de tarefas);
     e.	Gerenciadores de pacotes (Chocolatey, OneGet, etc...);
12.	19:30 Visualização e Máquinas Virtuais.
[](
https://www.youtube.com/watch?v=T7lCM3l7vAQ&

)

**Comment by LFPires1993** [comment]
Parabéns aos envolvidos, material útil 💪
