### ISSUE TITLE
[Desafio] Somar todos dígitos de um número

### ISSUE THREAD

**Issue by npoletto** [cwi-reset/edicao-02-qualificatoria#42]
O desafio é somar todos os dígitos de um número, caso a resposta possua mais do que um dígito, continuar somando até sobrar apenas um dígito.

Exemplos:
15 = 1 + 5 = **6**
279 = 2 + 7 + 9 = 18 = 1 + 8 = **9**
34567 = 3 + 4 + 5 + 6 + 7 = 25 = 2 + 5 = **7**

Já realizei o desafio, tem como resolver com uma função que chama ela própria (recursiva), mas também tem uma solução super simples, e rápida (quando você perceber vai se surpreender, caso não consiga encontrar).
 
Este desafio é muito interessante para verificar formas diferentes de fazer a mesma coisa.

Tentem resolver, depois postarei as duas soluções que mencionei.
:)

**Comment by greicekelly** [comment]
Boa noite , divertido o desafio, fiquei curiosa para ver as outras formas de resolver

segue a forma que encontrei 

```javascript

function somarDigitos(numero){

 soma = 0
 function somarArray(numero){
   soma = 0
    for(i=0; i < numero.toString().length; i++){

      numeros = numero.toString()[i]
      soma = soma + parseInt(numeros)
    }
  }
  
somarArray(numero)

  if(soma.toString().length > 1){
    somarArray(soma)
  }
  if(soma.toString().length == 1){
     return soma
    
  }
  
}
console.log(somarDigitos(34567))`

**Comment by npoletto** [comment]
> Boa noite , divertido o desafio, fiquei curiosa para ver as outras formas de resolver
> 
> segue a forma que encontrei
> 
> ```js
> function somarDigitos(numero){
> 
>  soma = 0
>  function somarArray(numero){
>    soma = 0
>     for(i=0; i < numero.toString().length; i++){
> 
>       numeros = numero.toString()[i]
>       soma = soma + parseInt(numeros)
>     }
>   }
>   
> somarArray(numero)
> 
>   if(soma.toString().length > 1){
>     somarArray(soma)
>   }
>   if(soma.toString().length == 1){
>      return soma
>     
>   }
>   
> }
> console.log(somarDigitos(34567))`
> ```

Tem um detalhe, se a primeira soma retornar um número de 3 dígitos, e a segunda vez que somar retornar um número de 2 dígitos, o código vai parar e não vai terminar.
Nos casos de números muito grandes iria falhar. Mas para números menores funcionou tudo ok! 
:)

**Comment by elciodalosto** [comment]
Segue a minha solução. Usei o prompt para o usuário digitar os numeros que quiser, daí da pra testar a lógica na prática


```
numero=prompt()
soma=0
texto=numero.toString()

for(i=0; i<texto.length; i++){
  soma += parseInt(texto[i])

}
console.log(soma)
```

**Comment by elciodalosto** [comment]
agora q vi q faltou um pedaço do código... se sobrar um número que contenha mais de um dígito, ele deve rodar novamente a lógica. Vou consertar kkkk

**Comment by npoletto** [comment]
> agora q vi q faltou um pedaço do código... se sobrar um número que contenha mais de um dígito, ele deve rodar novamente a lógica. Vou consertar kkkk

Sim! heheh.

Basta colocar isso como uma função que recebe um número, e fazer o seguinte:
```
if(soma<10) return soma
else return somaDigitos(soma)
}
```

Desta forma ele vai chamar a própria função quantas vezes for necessário.

Está ótima a solução! 
Mas ainda tem uma bem interessante e bem curta (apenas uma linha).

**Comment by elciodalosto** [comment]
Segue correção:

```
function somaTudo(valor){
  numero=valor
  soma=0
  numeroSeparado=numero.toString()

  for(i=0; i<numeroSeparado.length; i++){
    soma += parseInt(numeroSeparado[i])
  }
  if(soma > 9){
    somaTudo(soma)
  }
  return soma
}

somaTudo(prompt("Digite um numero: "))
```

**Comment by npoletto** [comment]
Bem, vou colocar a solução mais curta possível, que é super interessante:

```
function somaDigitos(n) {
	return ( (n-1) % 9 + 1) //o operador % é para calcular o resto da divisão
}
```

Este desafio um professor propôs mais de 15 anos atrás e achei bem bacana.
Isso ocorre por que há a seguinte correspondência:

1 = 1
2 = 2
3 = 3
...
8 = 8
9 = 9
10 = 1
11 = 2
...
18 = 9
19 = 1
...

Ou seja, o resultado varia de um em um, e após o nove ele não zera, mas vira um. E repete infinitamente. Por isso que o resto da divisão por nove funciona. A subtração por um, para logo fazer uma adição em um é para evitar que os múltiplos de 9 dessem resposta zero, não influenciando nos demais números não múltiplos de zero.

Obs: Apesar de curtir muito este desafio, na época que foi proposto não fui o aluno que conseguiu chegar a esta resposta, um colega conseguiu antes... :)

**Comment by lokyrech** [comment]
Maneiro, a forma que você apresentou no final @npoletto...

Esse aqui foi um dos desafios que mais me deram trabalho! Estas de parabéns! hehehe
Segue meu resultado:

```javascript
function somadorDeDigitos(numero){
  numeroTexto = numero.toString();
  soma = 0;

  for(i = 0; i < numeroTexto.length;i++){
    soma += parseInt(numeroTexto[i]);
  }

  if(soma > 9){
    soma = somadorDeDigitos(soma);
  }

  return soma;
}

function app(numero){

  if(!Number.isInteger(numero)){
    return "Valor informado inconsistênte."
  } else {
    return somadorDeDigitos(numero);
  }

}

numero = parseInt(prompt("Informe o número: "));

console.log(app(numero))
```

**Comment by npoletto** [comment]
> ```js
>   if(!Number.isInteger(numero)){
> ```

@lokyrech, muito legal teres verificado a consistência do parâmetro passado para função, esta preocupação é muito importante quando se desenvolve sistemas robustos.
Porém vou sugerir um desafio dentro do desafio: Consegue perceber alguma entrada do usuário que fará o programa falhar, mesmo com esta verificação?

Coincidentemente eu tive este problema ontem, e quebrei a cabeça para resolver. Eu precisava aceitar apenas dígitos numéricos, porém entradas de números negativos também passam pela verificação do isInteger(numero), e quando a função for verificar o sinal de menos (-), vai dar problema. 

Não sei se a solução que eu encontrei é a mais elegante, ou a mais correta, mas funcionou, vou compartilhar aqui:

`
/[^0-9]/.test(entrada)
`

Existem as expressões regulares em Javascript [(link para referência)](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Regular_Expressions). 
Este código vai testar se há algo além de números de 0 a 9 na string (o acento circunflexo é uma negação), logo, basta inverter o resultado deste teste para retornar true apenas se a expressão tiver exclusivamente dígitos de 0 a 9.

Ficando assim:
`
if ( !( /[^0-9]/.test(numero) ) ) { //repare no ponto de exclamação para inverter o resultado.
`

:)

**Comment by greicekelly** [comment]
> > Boa noite , divertido o desafio, fiquei curiosa para ver as outras formas de resolver
> > segue a forma que encontrei
> > ```js
> > function somarDigitos(numero){
> > 
> >  soma = 0
> >  function somarArray(numero){
> >    soma = 0
> >     for(i=0; i < numero.toString().length; i++){
> > 
> >       numeros = numero.toString()[i]
> >       soma = soma + parseInt(numeros)
> >     }
> >   }
> >   
> > somarArray(numero)
> > 
> >   if(soma.toString().length > 1){
> >     somarArray(soma)
> >   }
> >   if(soma.toString().length == 1){
> >      return soma
> >     
> >   }
> >   
> > }
> > console.log(somarDigitos(34567))`
> > ```
> 
> Tem um detalhe, se a primeira soma retornar um número de 3 dígitos, e a segunda vez que somar retornar um número de 2 dígitos, o código vai parar e não vai terminar.
> Nos casos de números muito grandes iria falhar. Mas para números menores funcionou tudo ok!
> :)

sim, obrigado pela observação, achei onde estava o erro para corrigir :)

muito interessante poder ver tantas formas de resolver o mesmo problema

**Comment by Lorandi** [comment]
**SOLUÇÃO DESAFIO SOMA por @npoletto** 
```javascript

/*Objetivo:O desafio é somar todos os dígitos de um número, caso a resposta possua mais do que um dígito, continuar somando até sobrar apenas um dígito.

Exemplos:
15 = 1 + 5 = 6
279 = 2 + 7 + 9 = 18 = 1 + 8 = 9
34567 = 3 + 4 + 5 + 6 + 7 = 25 = 2 + 5 = 7
*/

//Variáveis
let numero;
let numeroToString;
let numeroFinal;

function soma(numero){
        numeroToString = numero.toString();        
            
        do{        
        numeroFinal = 0;
        for(i=0; i < numeroToString.length; i++){                
                numeroFinal += parseInt(numeroToString[i])                 
        }
        numeroToString = numeroFinal.toString();
        
        } while(numeroFinal>9)
        console.log(numeroFinal)      
}

soma(9);                //9
soma(18);               //9
soma(27);               //9
soma(108);              //9
soma(207);              //9
soma(111111111);        //9                               

```

Resolver esse desafio em uma linha é sacanagem

**Comment by alefjgdr** [comment]
Deixo aqui a minha participação, achei muito legal o desafio. Seguindo o exemplo do colega @lokyrech, realizei uma verificação no parâmetro passado para a função, aceitando apenas números de 0-9 tanto em string como em números inteiros.


```javascript
function somarDigitos(valorInformado){
  var nan = false;
  var frase = "";
  var soma = 0;
  var digito = 0;
  /* VARIAVEIS INICIAIS PARA O REPETIDOR */
  var first = true;
  var tamanho = valorInformado.toString().length;
  var repetir = valorInformado.toString();
  var valorFrase = valorInformado.toString();
  /* VERIFICA SE O DIGITO INFORMADO É UM NUMERO SIMPLES OU COMPOSTO */
  if(valorInformado.toString().length > 1){
    do{
      /* VERIFICA SE É A PRIMEIRA PASSAGEM PELO REPETIDOR, PARA ENTAO ALTERAR OS VALORES NAS PROXIMAS PASSAGENS */
      if(first == true){
        first = false;
      }else{
        /* RESETA AS VARIAVEIS INICIAIS DO REPETIDOR PARA AS PROXIMAS PASSAGENS */
        tamanho = soma.toString().length;
        repetir = soma.toString();
        valorFrase = soma
        frase = ""
        soma = 0;
      }
      /* REPETIDOR PARA VERIFICAR DIGITO POR DIGITO PARA SABER SE ALGUM É NaN */
      for(index=0;index<tamanho;index++){
        digito = parseInt(repetir.substring(index,index+1))
        if(digito === 0 || digito === 1 || digito === 2 || digito === 3 || digito === 4 ||
          digito === 5 || digito === 6 || digito === 7 || digito === 8 || digito === 9){
          /* FORMA A FRASE DE SOMA, E REALIZA UMA NOVA SOMA A CADA PASSAGEM PELO REPETIDOR */  
          frase += digito.toString() + " + ";
          soma += digito;  
        }else{
          console.log("O valor informado não é um número inteiro!");
          nan = true
          break;
        }
      }
      /* BLOQUEIA A APRESENTAÇÃO DA FRASE CASO ALGUM DOS DIGITOS NÃO SEJA NUMERICO */
      if(nan != true){
        console.log(valorFrase, " = ", frase.substring(0,(frase.length - 3)), " = ", soma);
      }
    }while(soma > 9 && nan !== true)
  }else{
    console.log("Só é possivel a soma de números compostos!");
  }
}
```

**Comment by alexlimaxv** [comment]
Boa  noite pessoal!
Para esse desafio eu criei uma função que recebe um número como parâmetro. Logo após receber esse número eu converto o mesmo numa string e depois testo para saber o tamanho da string. Se o tamanho da string for igual 1 então eu retorno o próprio número de entrada. Se o tamanho da string for maior que 1 então ele entra num laço for e vai somando os dígitos.
Segue a minha versão:

```JavaScript
function somaDigitos(num){
  let soma=0;
  number = num.toString();
  if(number.length==1){
    return soma = parseInt(number.charAt(0));
  }else{
      for(i=0;i<number.length;i++){
        soma += parseInt(number.charAt(i));
      }
      return soma;
    }
}
console.log(somaDigitos(2)); // o resultado da soma é o proprio 2 nesse outro caso
console.log(somaDigitos(2351)); // o resultado da soma é 11 nesse caso

```

**Comment by Lorandi** [comment]
> string e depois testo para saber o tamanho da string. Se o tamanho da string for igual 1 então a função pega o caracter referente a posição de indicie zero (0) da String, ou seja a primeira posição dado que a String somente tem o numero de um digito, logo após a String é novamente convertida num número inteiro e assim retornado pela função. Se o tamanho da string for maior que 1 digito então o programa entra num laço For, então a String é convertida para um numero inteiro, e assim vai


Olá @alexlimaxv 
O `return soma `da linha 9 tem que estar dentro do for para ficar no laço. Do contrário o resultado ainda terá dois caracteres.
```javascript

function somaDigitos(num){
    let soma=0;
    number = num.toString();
    if(number.length==1){
      return soma = parseInt(number.charAt(0));
    }else{
        for(i=0;i<number.length;i++){
          soma += parseInt(number.charAt(i));
          return soma;
        }
        
      }
  }
  console.log(somaDigitos(2)); // 2
  console.log(somaDigitos(2351)); // 2
```

**Comment by alexlimaxv** [comment]
Olá @Lorandi se return ficar dentro do laço ele vai retornar o valor da soma todas as vezes que o laço repetir. Por isso coloquei fora porque quando o laço FOR acabar ele vai retornar o valor total da soma.

**Comment by Lorandi** [comment]
> Olá @Lorandi se o return ficar dentro do laço ele vai retornar o valor da soma todas as vezes que o laço repetir. Por isso coloquei fora porque quando o laço FOR acabar ele vai retornar o valor total da soma.

errei aqui. é que ele não estão retornando só um um caractere. só um instante

**Comment by Lorandi** [comment]
> Olá @Lorandi se o return ficar dentro do laço ele vai retornar o valor da soma todas as vezes que o laço repetir. Por isso coloquei fora porque quando o laço FOR acabar ele vai retornar o valor total da soma.

Estou com dificuldade de achar uma solução usando o `number.legth` pois quando a soma da um número com dois caracteres, ele já vai ter saído do for.

**Comment by alexlimaxv** [comment]
Olá @Lorandi quando você pede para retornar um valor logo no primeira passagem do laço você está informando que o programa vai executar a instrução antes do return e depois que ele executar esse bloco dentro do for ele retorna o valor e sai da função. Sendo assim o programa somente roda a primeira vez no laço. Por isso ele retorna o valor 2.

**Comment by Lorandi** [comment]
> Olá @Lorandi quando você pede para retornar um valor logo no primeira passagem do laço você está informando que o programa vai executar a instrução antes do return e depois que ele executar esse bloco dentro do for ele retorna o valor e sai da função. Sendo assim o programa somente roda a primeira vez no laço. Por isso ele retorna o valor 2. Eu testei a mudança que você enviou aqui e está acontecendo isso. Se fosse possível debugar no Repl.it você iria poder perceber isso.

Modifiquei aqui para continuar somando até ficar com apenas um caracter.

Adicionei mais uma verificação com if para rodar depois do primeiro laço.

```javascript
function somaDigitos(num){
    let soma=0;
    number = num.toString();
    if(number.length==1){
      return soma = parseInt(number.charAt(0));
    }else{
        for(i=0;i<number.length;i++){
          soma += parseInt(number.charAt(i));
         }

         if (soma <= 9){
            return soma;
         }
         else{
             do{
                 somaTemp = 0;
                 somaString = soma.toString()
                 for(i=0; i < somaString.length; i++){                
                    somaTemp += parseInt(somaString[i])
                }
                somaString = somaTemp.toString();
            }while(somaTemp>9)
            soma = somaTemp;
            return soma;                           
        }  
      }
  }
console.log(somaDigitos(2)); //2
console.log(somaDigitos(2351)); //2
console.log(somaDigitos(7992312398)) //8
console.log(somaDigitos(123456789)) //9
```

**Comment by alexlimaxv** [comment]
Ok @Lorandi percebi o erro no programa. Vou tentar a minha versão, não havia percebido que deveria retornar um numero somente com um digito. Obrigado por me alertar sobre isso.

**Comment by SaimonFill** [comment]
Muito interessante o desafio, segue minha solução:

`function fazSomaDosNumeros(numero){
  soma = 0
  numeroEmTexto = numero.toString()

  for(i = 0; i < numeroEmTexto.length; i++){
    soma = soma + parseInt(numeroEmTexto[i])
  }

  if(soma > 9){
    fazSomaDosNumeros(soma)
  }
  return soma
}

console.log("Soma dos números retornou: " + fazSomaDosNumeros(34567))`

**Comment by SaimonFill** [comment]
Muito bom o desafio, segue minha solução:

```javascript
function fazSomaDosNumeros(numero){
  soma = 0
  numeroEmTexto = numero.toString()

  for(i = 0; i < numeroEmTexto.length; i++){
    soma = soma + parseInt(numeroEmTexto[i])
  }

  if(soma > 9){
    fazSomaDosNumeros(soma)
  }
  return soma
}

console.log("Soma dos números retornou: " + fazSomaDosNumeros(34567))
```

**Comment by npoletto** [comment]
### Por que não complicar?

Tirando a solução em uma linha apenas (já apresentada aqui), qual outra solução possível sem usar Strings? (sem percorrer os caracteres um a um como se fosse um vetor de caracteres). Ou seja, apenas com operações matemáticas.
Um pouco mais difícil hein? 

<details>

  <summary> SOLUÇÃO CLIQUE AQUI </summary>
  
  ```
function somarDigitos(numero) {
  soma=0
  while (numero>0) {
  	soma += numero % 10   //soma o resto da divisão por 10
        numero = (numero - (numero % 10) ) / 10  //subtrai o número já somado, e desloca as casas decimais
  }
  
  if(soma<10) return soma
  else return somarDigitos(soma)
 }

```
  
 </details>
 
 Mas deixem para depois da prova, não vamos queimar mais neurônios. 
 Boa prova a todos e valeu as interações no desafio!

**Comment by SaimonFill** [comment]
> ### Por que não complicar?
> Tirando a solução em uma linha apenas (já apresentada aqui), qual outra solução possível sem usar Strings? (sem percorrer os caracteres um a um como se fosse um vetor de caracteres). Ou seja, apenas com operações matemáticas.
> Um pouco mais difícil hein?
> 
>  SOLUÇÃO CLIQUE AQUI
> ```
> function somarDigitos(numero) {
> soma=0
> while (numero>0) {
> 	soma += numero % 10   //soma o resto da divisão por 10
>       numero = (numero - (numero % 10) ) / 10  //subtrai o número já somado, e desloca as casas decimais
> }
> 
> if(soma<10) return soma
> else return somarDigitos(soma)
> }
> ```
> 
> Mas deixem para depois da prova, não vamos queimar mais neurônios.
> Boa prova a todos e valeu as interações no desafio!

estava mesmo tentando fazer sem usar o toString() haha 
sempre é bom ver mais de uma forma de resolver os problemas

**Comment by Volneigm** [comment]
Bom dia pessoal! Muito legal esse exercício proposto pelo @npoletto. 
Analisando o código de uma linha proposto por ele, fiz de uma outra forma:

`function somarDigitosNumero(valor){
  return valor % 9 == 0 ? 9 : valor % 9
}
console.log(somarDigitosNumero(88))`

Dessa forma, com o uso do operador ternário verifica-se o modulo do valor solicitado é igual a zero, caso for retorna 9, caso contrario retornará o modulo do numero passado na chamada da função.

**Comment by Lorandi** [comment]
> Bom dia pessoal! Muito legal esse exercício proposto pelo @npoletto.
> Analisando o código de uma linha proposto por ele, fiz de uma outra forma:
> 
> ```js
> function somarDigitosNumero(valor){
>   return valor % 9 == 0 ? 9 : valor % 9
> }
> console.log(somarDigitosNumero(88))
> ```
> 
> Dessa forma, com o uso do operador ternário verifica-se o modulo do valor solicitado é igual a zero, caso for retorna 9, caso contrario retornará o modulo do numero passado na chamada da função.

Excelente solução. Incrível como o uso do % é útil. Eu só via sendo usado no contexto de determinar um número era par ou impar.

```javascript
function parOuImpar(valor){
  return valor % 2 == 0 ? "par" : "impar";
  }
console.log(parOuImpar(3)); //impar
console.log(parOuImpar(45)); //impar
console.log(parOuImpar(4)); //par
```

**Comment by Lorandi** [comment]
> Muito bom o desafio, segue minha solução:
> 
> ```js
> function fazSomaDosNumeros(numero){
>   soma = 0
>   numeroEmTexto = numero.toString()
> 
>   for(i = 0; i < numeroEmTexto.length; i++){
>     soma = soma + parseInt(numeroEmTexto[i])
>   }
> 
>   if(soma > 9){
>     fazSomaDosNumeros(soma)
>   }
>   return soma
> }
> 
> console.log("Soma dos números retornou: " + fazSomaDosNumeros(34567))
> ```

Legal, fez uma função recursiva, que chama ela mesma.

É uma ótima estratégia para usar no código do @alexlimaxv , bem mais simples do que a solução que eu tinha dado.

```javascript
function somaDigitos(num){
    soma=0;
    number = num.toString();
    if(number.length==1){
      return soma = parseInt(number.charAt(0));
    }else{
      for(i=0;i<number.length;i++){
      soma += parseInt(number.charAt(i));
      }
      if (soma <= 9){
        return soma;
      }else{
        somaDigitos(soma)
        //  do{
        //      somaTemp = 0;
        //      somaString = soma.toString()
        //      for(i=0; i < somaString.length; i++){                
        //         somaTemp += parseInt(somaString[i])
        //     }
        //     somaString = somaTemp.toString();
        // }while(somaTemp>9)
        // soma = somaTemp;                                   
      }      
    }
    return soma;
  }
console.log(somaDigitos(2)); //2
console.log(somaDigitos(2351)); //2
console.log(somaDigitos(7992312398)) //8
console.log(somaDigitos(123456789)) //9
```

**Comment by Lorandi** [comment]
NOVA SOLUÇÃO USANDO FUNÇÃO RECURSIVA
Inspirado pelo @SaimonFill pelas funções recursivas e provocado pelo @npoletto para não usar toString() fiz essa outra implementação.

```javascript
function somaDigitos(n){   
  while(n>10){
    n = n % 10 +somaDigitos(Math.floor(n/10));
    somaDigitos(n)
  }    
  return n;  
}

console.log(somaDigitos(2)); //2
console.log(somaDigitos(2351)); //2
console.log(somaDigitos(7992312398)) //8
console.log(somaDigitos(123456789)) //9
console.log(somaDigitos(9999999999999)) //9
```
