### ISSUE TITLE
Link da Live de 12/01/2021 - Não recebi o e-mail, postem aqui por gentileza! :D

### ISSUE THREAD

**Issue by elciodalosto** [cwi-reset/edicao-02-qualificatoria#43]
Link da live de 12/01/2021 - Manda aí quem tiver. 
Agradecido.

**Comment by LeonardoBerlatto** [comment]
https://vimeo.com/event/589315/videos/497263677/e413499e5e

**Comment by elciodalosto** [comment]
Muito obrigado Leonardo, salvou aqui

**Comment by CarlosBueno3000** [comment]
Valeu!!!! 

Não consigo concluir alguma coisa no Vimeo. Só abre no navegador e não consigo comentar por lá...

**Comment by MoraesJorge** [comment]
Olá @CarlosBueno3000 , tudo certo?
Já tentou mudou o navegador? Firefox ou Microsoft Edge?

Segue os link das lives até o momento:

1º live
https://vimeo.com/495292971/79ec85490e

2º live
https://vimeo.com/497262923/7335d9033c

3º live
https://vimeo.com/event/589315/videos/497263677/e413499e5e

Espero ter ajudado. Qualquer coisa, eu pode postar um print para vermos se há algo de errado.

**Comment by CarlosBueno3000** [comment]
Tentei ate no famigerado do Internet Explorer. Aderi a um plano de assinatura. Aparentemente estou num programa para postar vídeos, não para assistir. 
Não abre o chat nos navegadores, fica apenas zerado. Consigo apenas curtir e aumentar o som..
![Screenshot_20210112-203800](https://user-images.githubusercontent.com/76565807/104387600-3b738500-5516-11eb-9897-a81ace6618f5.jpg)

**Comment by MoraesJorge** [comment]
Já tentou em um PC, ao invés do _mobile_?
Mesmo no modo _free_ é possível assistir às live e comentá-las ao vivo.

**Comment by elciodalosto** [comment]
Se alguém tem o link de avaliação da última live, manda aí por gentileza.

**Comment by CarlosBueno3000** [comment]
> Já tentou em um PC, ao invés do _mobile_?
> Mesmo no modo _free_ é possível assistir às live e comentá-las ao vivo.

Sim tentei no PC, todos os navegadores. Nada. Logado, offline. Estas duas ultimas lives apenas assisti.

**Comment by EduardaBatistella** [comment]
@CarlosBueno3000 estou com o mesmo problema. Não consigo comentar, só assistir.  Ocorreu nas duas ultimas lives.

**Comment by CarlosBueno3000** [comment]
Na live anterior perdi uns pedaços. Ontem fui mais atento, abri no PC e fiz o que podia no celular. Como não deu certo, voltei pro PC e foram 5 navegadores, Crhome, Brave, Mozila, IE e o Edge. Todos no mesmo formato. Ah sim, a central de ajuda do Vimeo só possui artigos para auxiliar quem está produzindo um vídeo, quem vai assistir que lute... rsrsrsrsrs.

Mas tranquilo, tenho acompanhado aqui e qualquer duvida que tirem durante a live já me auxilia! Estou acompanhando a maioria das Issues aqui. Então, tudo é aprendizado!

Comecei ano passado à estudar programação por conta aqui. Nem esperava que uma oportunidade como o Reset surgisse em minha frente agora (engatinhando no Python, entrando no mundo 3 do Guanabara, bases numéricas, lógica com o pseudo-código e o curso antigo de HTML 5)! Não é nem um passo largo é um salto pra mim!!!

O que vier pela frente é lucro de pirâmide!!! rsrsrsrsrs

**Comment by TanisiaFernandes** [comment]
Também ocorre comigo. Na primeira live consegui comentar, nas outras não consegui de forma alguma!

**Comment by CWI-RH** [comment]
> Link da live de 12/01/2021 - Manda aí quem tiver.
> Agradecido.

Boa tarde pessoal!

Link para assistir a gravação da live do dia 12/01: https://vimeo.com/event/589315/videos/497263677/e413499e5e

Link da pesquisa da live do dia 12/01: https://forms.gle/7VU5Fb1h8bdJaNY96
