### ISSUE TITLE
Exercícios de preparação para a prova

### ISSUE THREAD

**Issue by FelipeLT** [cwi-reset/edicao-02-qualificatoria#44]
Fala galera... 

Segue uma dica para quem deseja praticar programação em várias linguagens e níveis de dificuldade. 
Recomendo um esforço por lá.

https://www.urionlinejudge.com.br/judge/pt

Cria a tua conta, escolhe a linguagem que deseja praticar e bons estudos
Os resultados da minha pratica eu adiciono no Github. 

Bora

**Comment by dudusouza** [comment]
Obrigado Felipe!

**Comment by CarlosBueno3000** [comment]
Bah! Meu piá vive me cobrando: "Tá fazendo teus exercícios na URI?", no mínimo duas vezes por semana...

**Comment by alexlimaxv** [comment]
Olá pessoal alguém sabe o link para live de hoje? Infelizmente perdi a noção do tempo estudando para a prova e só notei agora que ja passam das 20 horas.

**Comment by SaimonFill** [comment]
> Fala galera...
> 
> Segue uma dica para quem deseja praticar programação em várias linguagens e níveis de dificuldade.
> Recomendo um esforço por lá.
> 
> https://www.urionlinejudge.com.br/judge/pt
> 
> Cria a tua conta, escolhe a linguagem que deseja praticar e bons estudos
> Os resultados da minha pratica eu adiciono no Github.
> 
> Bora

Muito boa a dica!

Esses exercícios da URI são muito bons para praticar, principalmente os iniciais que englobam o que estamos estudando nessa etapa.
