### ISSUE TITLE
Link da prova

### ISSUE THREAD

**Issue by TenoEngineer** [cwi-reset/edicao-02-qualificatoria#45]
Boa noite, pessoal!
Eu ainda não recebi o e-mail da prova. Aconteceu somente comigo? 
Se alguém puder disponibilizar o link para mim.
Desde já, agradecido.

**Comment by Lucas-Bavaresco** [comment]
@TenoEngineer , verifica se não entrou no teu e-mail como SPAM / Lixo Eletrônico. Caso contrário, envie e-mail solicitando para reset@cwi.com.br, conforme orientado na LIVE pelo professor @AlexandreSNeto ok ? Espero ter ajudado...

**Comment by AlexandreSNeto** [comment]
@TenoEngineer O e-mail que temos aqui, ao qual fizemos o envio é o heitortmuller@gmail.com
Por favor, conforme o Lucas comentou, verifique se não está no spam. Caso contrario farei o reenvio. Apenas me confirme

**Comment by TenoEngineer** [comment]
Eu verifiquei o spam, não encontrei nada. Vou encaminhar um e-mail pro reset.
Obrigado pessoal!
