### ISSUE TITLE
Ensinamento Continuo

### ISSUE THREAD

**Issue by Felipe-F-Coelho** [cwi-reset/edicao-02-qualificatoria#47]
Bom dia Pessoal!

Gostei muito de todo os ensinamentos passados aqui por vocês e adoraria poder continuar meus estudos para aperfeiçoar minhas habilidades em programação.

Teria a possibilidade de fazer a indicação de alguns cursos para iniciantes em Java e JavaScript? Se tiverem também cursos bons de lógica de programação seria ótimo.

Obs:. As avaliações ainda não foram lançadas, não sei se passei ou não mas quero continuar estudando!! :D

Desde já, deixo meu agradecimento por tudo!
Felipe Coelho

**Comment by Davidjordao** [comment]
**Bom dia @Felipe-F-Coelho ,**

Somos colegas da fase qualificatória, acredito que não fui muito bem na prova porque estava bem atarefado no dia, mas de qualquer forma também estou aguardando ansiosamente pelos resultados.

### Para contribuir conheço alguns "cursos"

Esse canal 👇, apesar dos videos antigos, tem um conteúdo muito bem estruturado:
[De aluno para aluno](https://www.youtube.com/c/ItaloGross/featured)

Tem os cursos do Khan Academy que são mundialmente conhecidos pela didática(tem de tudo lá no site deles):
[Unit: Algorithms](https://www.khanacademy.org/computing/computer-science/algorithms)

Vunesp - mais formal:
[Programação Orientada a Objetos - Java](https://www.youtube.com/playlist?list=PLxI8Can9yAHewZWSrlhpId71bk5N_W7W1)

No entanto, nem tudo tem no youtube, então, quando quero me aprofundar em algum assunto, utilizo alguns meios para conseguir aprender sozinho.


### Por Exemplo:
Quando quero aprender um tópico que já é "manjado" (consolidado) , seja Matemática, Física básica, Cálculo, Circuitos Digitais, ou até mesmo programação, procuro em planos de ensino de universidades.

[Exemplo: Matriz Curricular- Ciência da Computação - UNIPAMPA](http://cursos.unipampa.edu.br/cursos/cienciadacomputacao/files/2019/02/sequencia-aconselhavel-2019.pdf)

Então se deseja aprender programação, você pode ir até o site de qualquer universidade publica entrar na matriz curricular do curso e ler sobre as disciplinas. Nesse caso pode ser do seu interesse a disciplina de algoritmos, então basta procurar pelo plano de ensino da mesma.
_(O MEC obriga cursos de engenharia a ter carga horaria minima com tópicos em informatica, então é bem tranquilo achar conteúdos sobre logica de programação, algoritmos e etc)_

[Exemplo: Plano de Ensino - Algoritmos UTFPR](https://sistemas2.utfpr.edu.br/dpls/sistema/acad00/mpPlanoEnsinoInformativo.pcPrintInfoPlaEns?p_Disccodnr=2673&p_Plaenscodnr=7304&p_Unidcodnr=6) 

[Exemplo: Plano de Ensino - Estrutura de Dados - UNESP ](https://www.ibilce.unesp.br/Home/Pos-Graduacao475/CienciadaComputacao/estrutura-de-dados-atualiz-2018_corrigida.pdf)

No Plano de ensino você pode encontrar o objetivo da disciplina, a ementa, o conteúdo programático, e o mais importante a bibliografia básica. Com isso você é capaz de identificar tudo oque é cobrado, e ter uma linha de base para onde seguir nos estudos. _( a partir daqui você pode procurar aulas no youtube ou livros que expliquem os tópicos em especifico , ou seja, já da pra se virar sozinho)_

Entretanto essa "técnica" funciona bem para assuntos consolidados, ou até mesmo o estado da arte. Para um tema ser publicado em um livro ou entrar para a grade de uma universidade, exige ele que cumpra diversas etapas e isso leva tempo. Desta forma, nem sempre você vai encontras os assuntos mais recentes na grade das universidades, mas certamente o que importa aqui é ter a base e know-how, assim você é capaz de aprender qualquer  novo dentro do tópico de interesse.

**Comment by Lorandi** [comment]
Ressalto também essa plataforma chamada +PraTi  que inclusive a CWI é mantenedora https://www.maisprati.com.br/

**Comment by SaimonFill** [comment]
Todas essas dicas dadas pelos colegas são muito boas, principalmente o +PraTi.

Tem também os cursos da Udemy, Alura ... que são bem recomendados

**Comment by Lorandi** [comment]
@SaimonFill eu tb curto a Alura. 

Alias, para quem se interessa em front-end, eles estão com uma imersão gratuita na próxima semana em React e Next.js. 

Pelo que ví numa live,  apesar de ser focada nessas bibliotecas, a imersão também serve para quem tem pouco conhecimento na área. 

Inscrições pelo link https://www.alura.com.br/imersao-react-next-js

**Comment by marcosrsalles** [comment]
Olá @Felipe-F-Coelho,

te recomendo este site de cursos de universidades espalhadas pelo mundo, tem bastante coisa de TI.
https://pt.coursera.org/
os cursos para ganhar certificado são pagos, mas eles tem auxilio que sai custo 0 e com certificado.

Esses dias recebi e-mail que a FIAP On esta com alguns cursos gratuitos na área de TI, se tu te interessar:
https://on.fiap.com.br/local/movimentobrasildigital/

Na IGTI também tem belos cursos:
https://www.igti.com.br/

Se tu procurar no YouTube também tem vários canais legais que ensinam bastante coisa de programação, inclusive lógica.

Para cursos com preço acessível te recomendo a Udemy.

Todos esses sites que passei são conteúdos em vídeo, mas lembrando que ler também é bem interessante, te recomendo este site:
https://www.casadocodigo.com.br/

Bons estudos.
abraço

**Comment by nobregadanilo** [comment]
Eu to fazendo na alura e tenho gostado

**Comment by SaimonFill** [comment]
Estava "futricando" na internet e achei um repositório no GitHub, que o Felipe Deschamps compartilhou, onde tem diversos livros de programação grátis e de diversas linguagens de diferentes níveis e com várias opções de idiomas, inclusive tem uma seção de livros em português: 

https://github.com/EbookFoundation/free-programming-books

**Comment by MTheobald86** [comment]
Excelente achado @SaimonFill. Obrigado por compartilhar!
