### ISSUE TITLE
Sobre outras ferramentas e ideias para imersão em programação

### ISSUE THREAD

**Issue by nobregadanilo** [cwi-reset/edicao-02-qualificatoria#49]
Gente, estava procurando outros materiais pra me manter imerso no conteúdo e achei algumas coisas que soaram legais, queria saber o que vocês acham e se tem dicas.

   Esse link fala de apps pra facilitar o aprendizado, vou começar a testar amanhã. Minha ideia é achar algo que eu possa visitar em pequenos momentos de ócio, principalmente se for algo meio gamificado pra tratar de logica em si, to querendo acertar a forma de pensar pra quando for pegar o código em si já estar com uma "cabeça voltada pra logica" saca?

https://usemobile.com.br/7-aplicativos-para-aprender-progamacao/

   Também pequei um livro pra ler, gosto muito de estudar a partir da leitura e acho que isso pode começar a aprofundar tanto a parte pratica quando o conteúdo de vídeos e tal, mas peguei um que me pareceu básico.

É "Logica de programação - Crie seus primeiros programas usando javascript e html" o nome, me indicaram os livros da casa do código e escolhi esse, tem PDF na net.

   O que vocês acham? tem mais dicas?

**Comment by csdamo** [comment]
@nobregadanilo , muito boa essa ideia de aplicativos para desenvolver o raciocínio para lógica. Neste contexto, eu indico o Kattis ([https://open.kattis.com/](url)). Ele apresenta diversos desafios, que possuem pontuação variada, conforme o nível de dificuldade, e tem pessoas do mundo inteiro que participam, mas você pode ver o seu ranking por país, por estado ou universidade, se for o caso.

Dos aplicativos que estão no site que você indicou, vou testar o Solo Learn, gostei da descrição dele! Obrigada pelas dicas!

**Comment by anatoniazzo** [comment]
Eu estava procurando também materiais para treinar mais a lógica e o raciocínio, agradeço pelas indicações. Concordo com @csdamo , gostei mais do SoloLearn. Obrigada pelas dicas!!

**Comment by Lorandi** [comment]
Essa sugestão já foi dada aqui no fóum, mas reforço o www.codewars.com. Sendo programação uma profissão de prática, me parece que o melhor aprendizado é fazendo, testando, errando. 

No codewars, depois que resolve um problema, pode ver como outros resolveram e assim ir melhorando e aprendendo.

Da para escolher o nível e tem uma pegada de gamificação pois vai liberando recursos a medida que resolve problemas.

Além de fortalecer a lógica da programação, tenho conhecido outros métodos que facilitam muito a vida.

Se fizerem sing in, me adicionem lá https://www.codewars.com/users/Lorandi

Bons estudos!

**Comment by anakrummenauer** [comment]
Ótimo esse artigo com os apps! Eu estou usando o Mimo desde o começo do Reset e ele é bem bacana para aprender o básico do básico de cada linguagem. Vou dar uma olhada também nestes outros indicados :)
