### ISSUE TITLE
Canais sobre programação no Youtube

### ISSUE THREAD

**Issue by Lorandi** [cwi-reset/edicao-02-qualificatoria#9]
Fala pessoal.

Além dos excelentes canais do Fabio Akita (https://www.youtube.com/channel/UCib793mnUOhWymCh2VJKplQ), do Filipe Deschamps (https://www.youtube.com/channel/UCU5JicSrEM5A63jkJ2QvGYw) e do Nerdologia Tech (https://www.youtube.com/watch?v=75IGjO5tJgo&list=PLyRcl7Q37-DU9HA99_Ob9Vh7M0nQw8pNV), citados no conteúdo opcional do material de estudo, gostaria de sugerir alguns outros que entendo terem muita qualidade:

- Alura Cursos Online - https://www.youtube.com/channel/UCo7EHzKF2zDFWszw7Dg4mPw
- Code Drip by Aaron Jack - https://www.youtube.com/channel/UCRLEADhMcb8WUdnQ5_Alk7g
- CS50 - https://www.youtube.com/channel/UCcabW7890RKJzL968QWEykA
- Curso em Vídeo - https://www.youtube.com/channel/UCrWvhVmt0Qac3HgsjQK62FQ
- Rocketseat - https://www.youtube.com/channel/UCSfwM5u0Kce6Cce8_S72olg

Quais outros vocês seguem?

**Comment by sergioribeiros** [comment]
Eu sigo também o Jhonatam do canal Dev Aprender

**Comment by pedropietro** [comment]
Canal do Fabio Akita - Playlist para iniciantes na programação - https://www.youtube.com/playlist?list=PLdsnXVqbHDUc7htGFobbZoNen3r_wm3ki

**Comment by MoraesJorge** [comment]
Valeu @Lorandi !!!
Vou dar um conferida no material sugerido.

**Comment by AlexsonT** [comment]
Olá, organizei a listagem e deixei minha contribuição. Bons estudos!

Alura Cursos Online - https://www.youtube.com/channel/UCo7EHzKF2zDFWszw7Dg4mPw
Code Drip by Aaron Jack - https://www.youtube.com/channel/UCRLEADhMcb8WUdnQ5_Alk7g
Código Fonte TV - https://www.youtube.com/c/codigofontetv/videos
CS50 - https://www.youtube.com/channel/UCcabW7890RKJzL968QWEykA
Curso em Vídeo - https://www.youtube.com/channel/UCrWvhVmt0Qac3HgsjQK62FQ
Dev Aprender - https://www.youtube.com/c/DevAprender/videos
Dev Media - https://www.youtube.com/c/DevmediaBrasil/videos
Fabio Akita - https://www.youtube.com/channel/UCib793mnUOhWymCh2VJKplQ
Filipe Deschamps - https://www.youtube.com/channel/UCU5JicSrEM5A63jkJ2QvGYw
HCode - https://www.youtube.com/channel/UCjWENuSH2gX55-y7QSZiWxA
Lucas Montano - https://www.youtube.com/c/LucasMontano/videos
Nerdologia Tech - https://www.youtube.com/watch?v=75IGjO5tJgo&list=PLyRcl7Q37-DU9HA99_Ob9Vh7M0nQw8pNV
Rocketseat - https://www.youtube.com/channel/UCSfwM5u0Kce6Cce8_S72olg

**Comment by renatolarrossa** [comment]
@Lorandi, dicas top!!! bora conferir ;)

**Comment by csdamo** [comment]
Ótimas dicas pessoal! Vou conferir!

Quero deixar uma contribuição com o site, FreeCodeCamp. Há vários exercícios para quem está começando do zero: https://www.freecodecamp.org/learn. 

Além disso, eles tem um canal no youtube com muito conteúdo:  https://www.youtube.com/c/Freecodecamp/videos.

**Comment by pedropietro** [comment]
Mais alguns links de valor: 

Digital Innovation One - https://www.youtube.com/channel/UCMxqhdELkftE8DuBZiwdPfg
Dev Eficiente - https://www.youtube.com/channel/UC9xYzttzFxK9cmhKPQCalYQ
WebSchool - https://www.youtube.com/channel/UCKdo1RaF8gzfhvkOdZv_ojg
Loiane Groner - https://www.youtube.com/channel/UCqQn92noBhY9VKQy4xCHPsg
Vinicius Ferraz - https://www.youtube.com/channel/UCJNOHl-pTTTj4S9yq60Ps9A
Otavio Lemos - https://www.youtube.com/channel/UC9cOiXh-RFR7KI61KcyTb0g

A lista com informações que vão desde o básico sobre programação e carreira até a tecnologias usadas no nosso cotidiano. Todos tem uma linguagem simples, clara e direta com exemplos demonstrativos de cada tecnologia citada.

**Comment by Lucas-Bavaresco** [comment]
Atualizando pessoal... 

Juntei todos, deixando a minha contribuição: Bons estudos! [2]

+ Pra Ti | CWI - https://www.youtube.com/c/maispraTI/
Alura Cursos Online | Paulo & Gabriel - https://www.youtube.com/user/aluracursosonline
Programador BR | Igor Oliveira: - https://www.youtube.com/channel/UCrdgeUeCll2QKmqmihIgKBQ
Cursos Em Vídeo | Gustavo Guanabara - https://www.youtube.com/user/cursosemvideo
DevSuperior | Nelio Alves - https://www.youtube.com/channel/UC3twHmWQwtqEO7u-gB_2f7g
Fabio Akita - https://www.youtube.com/channel/UCib793mnUOhWymCh2VJKplQ
Filipe Deschamps - https://www.youtube.com/channel/UCU5JicSrEM5A63jkJ2QvGYw
Sharpax GameDev | Marks Vinícius - https://www.youtube.com/channel/UCQR7hvIxWrtkCw5TZdufjlg
DevMedia | Estevão & Mateus - https://www.youtube.com/channel/UClBrpNsTEFLbZDDMW1xiOaQ
Nerdologia Tech - https://www.youtube.com/watch?v=75IGjO5tJgo&list=PLyRcl7Q37-DU9HA99_Ob9Vh7M0nQw8pNV
Lucas Montano - https://www.youtube.com/channel/UCyHOBY6IDZF9zOKJPou2Rgg
Dev Aprender - https://www.youtube.com/c/DevAprender/videos
HCode - https://www.youtube.com/channel/UCjWENuSH2gX55-y7QSZiWxA
Rocketseat - https://www.youtube.com/channel/UCSfwM5u0Kce6Cce8_S72olg
Digital Innovation One - https://www.youtube.com/channel/UCMxqhdELkftE8DuBZiwdPfg
Dev Eficiente - https://www.youtube.com/channel/UC9xYzttzFxK9cmhKPQCalYQ
WebSchool - https://www.youtube.com/channel/UCKdo1RaF8gzfhvkOdZv_ojg
Loiane Groner - https://www.youtube.com/channel/UCqQn92noBhY9VKQy4xCHPsg
Vinicius Ferraz - https://www.youtube.com/channel/UCJNOHl-pTTTj4S9yq60Ps9A
Otavio Lemos - https://www.youtube.com/channel/UC9cOiXh-RFR7KI61KcyTb0g
Code Drip by Aaron Jack - https://www.youtube.com/channel/UCRLEADhMcb8WUdnQ5_Alk7g
Código Fonte TV - https://www.youtube.com/c/codigofontetv/videos
CS50 - https://www.youtube.com/channel/UCcabW7890RKJzL968QWEykA
Craig Dennis | freeCodeCamp.org - https://www.youtube.com/c/Freecodecamp/videos.

Grato a todos.
